### ISSUE TITLE
quick filter destroyed massive amounts of email data by not respecting copy vs move in the filter

### ISSUE THREAD

**Issue by VincentJGeisler** [RealRaven2000/quickFilters#112]
I tried to create a filter that would copy specific email messages from the main inbox to a secondary mail folder if they had attachments. Unfortunately, the plugin does not appear to understand the difference between move and copy and had moved all the emails rather than copy.  This resulted in the destruction of 3 years of email data.

**Comment by RealRaven2000** [comment]
Did the action on the filter say copy or move? These are both standard filter methods from Thunderbird, so if they don't do what it says I would definitely raise a bug with the Thunderbird core team. Also how exactly did you create the filter - did you use the assistant and then copied the email to a folder?
