### ISSUE TITLE
Add support for the latest beta Thunderbird (103)

### ISSUE THREAD

**Issue by zertyuiop** [RealRaven2000/quickFilters#117]

**Comment by Amoeba00** [comment]
You can do this yourself (of course at your own risk)

Use your current archive/zip utility (like 7zip) and open the .xpi file
Open the manifest.json file listed inside
Look for "strict_max_version" and change it to something like "104.*"
Save the changes
Confirm the update to the .xpi file
Add that to TB 103+

Reminder:  Export your rules from your current QF to add them back in to the new install.
Hope that helps.

**Comment by slalaurette** [comment]
How can you export your rules if the addon is not working? My Thunderbird was autoupdated...

**Comment by RealRaven2000** [comment]
> How can you export your rules if the addon is not working? My Thunderbird was autoupdated...

Why are you using a beta version? I highly recommend installing the Thunderbird release version if you don't want to keep patching Add-ons. quickFilters is compatible with Thunderbird 102.* 
I could release a version without strict_max_version but there are too many issues in Thunderbird 102 ESR release that need to be fixed first...

**Comment by slalaurette** [comment]
I patched the .xpi, dragged it to the addon manager, and it's working fine. Thanks for this piece of software! It's awesome.

As for why I'm using a beta version... I honestly don't remember. I came back to Thunderbird after Google rendered Opera Mail unusable because of the lack of OAuth. The old version I had was too basic so I guess I grabbed the one with the highest number, haha. But I thought I was installing the stable release...

Anyway, I'll switch to the stable branch in the next iteration. 

Thank you!

**Comment by RealRaven2000** [comment]
> Use your current archive/zip utility (like 7zip) and open the .xpi file Open the manifest.json file listed inside Look for "strict_max_version" and change it to something like "104.*" Save the changes Confirm the update to the .xpi file Add that to TB 103+

You can also completely remove the line. I added it for safety because I cannot always test my Add-ons with beta versions.

**Comment by Amoeba00** [comment]
FWIW, I wound up going back to TB v91 - because the newer versions 102+ were corrupting random G-mail downloads via IMAP.  No issues with QF at all though.

**Comment by zertyuiop** [comment]
@Amoeba00 Try Betterbird, it might work better. I'm also thinking of rolling back to an earlier version of Thunderbird, in the current one, the size of folders on the disk began to grow uncontrollably (an account with ~ 2500-3000 letters began to take up more than 80 GB).

**Comment by RealRaven2000** [comment]
> @Amoeba00 Try Betterbird, it might work better. I'm also thinking of rolling back to an earlier version of Thunderbird, in the current one, the size of folders on the disk began to grow uncontrollably (an account with ~ 2500-3000 letters began to take up more than 80 GB).

Betterbird also supports the new "mixed any / all" (and + or) syntax, but I haven't fully patched quickFilters to work with these - so I cannot guarantee that backup / restore will work and definitely merge would break "mixed" filters. But it will definitely come in the future. Meaningful merging is tricky though.

**Comment by Amoeba00** [comment]
OK thanks for update - I'll give it a shot and see what happens.  Thanks!
