### ISSUE TITLE
Feature Request:  Filter Sorting

### ISSUE THREAD

**Issue by Amoeba00** [RealRaven2000/quickFilters#118]
While there is a setting to insert new filters in alphabetical order - I don't see how to sort the current set in alphabetical order - only move them manually.  Or is there a way to do this that I don't see? Thanks!

**Comment by RealRaven2000** [comment]
- highlight either all or a selection of filters that you want to sort
- use the sort filters button on the toolbar:

![image](https://user-images.githubusercontent.com/6314674/177844063-42685a5d-2484-4066-8c2e-94eaf60faaba.png)

**Comment by Amoeba00** [comment]
Right there in front of me.  Thanks!
