### ISSUE TITLE
Feature Request:  qF Assistant Customization

### ISSUE THREAD

**Issue by Amoeba00** [RealRaven2000/quickFilters#119]
When I drag an e-mail from the inbox or spam to the desired folder, the QF Assistant correctly auto-creates the default rule based on current selections.  

However, I'd like different defaults such as...
Only when the From: address/domain is detected (not the To: e-mail address)
OR
Only when the address is detected in To:/CC:/BCC:

Is there a way to edit or customize the QF Assistant to minimize the mouse clicks involved to create a rule?
Thanks!

**Comment by Amoeba00** [comment]
Ahh - ok - I tried creating a new template - but it wasn't working right.  Will try again and report back.  Thanks!

**Comment by Amoeba00** [comment]
Sorry for not being clear - this is what I'm trying to edit/modify ....

![Image161](https://user-images.githubusercontent.com/39176113/178157749-6b2a65d1-d6bd-48c1-94e3-d5cdbe017aa2.jpg)

Otherwise, when I follow the "template" steps all I'm doing is creating a filter - which I know how to do - or am I missing something?

**Comment by RealRaven2000** [comment]
> Sorry for not being clear - this is what I'm trying to edit/modify .... (Basically take your default template of "based on sender" and remove the second rule match that auto-adds the %to%)

![image](https://user-images.githubusercontent.com/6314674/178158373-a737d9cf-45e6-4fbc-aeac-0ba59352b4de.png)

**Comment by Amoeba00** [comment]
That was it.  Thanks!

**Comment by RealRaven2000** [comment]
> That was it. Thanks!

YW. You can still make more advanced new templates to select on the assistant screen that add more user-defined, auto-filled search conditions & additional actions. If you would also completely new types of actions / search terms check out the Add-on FiltaQuilla.

**Comment by Amoeba00** [comment]
> If you would also completely new types of actions / search terms check out the Add-on FiltaQuilla.

OK good to know - for now, that one preference setting was the only adjustment I needed, but good to know that options exist should I want to do a deep dive.  Have a great week!
