### ISSUE TITLE
Add keyboard shortcuts for Run Filters buttons

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#12]
This can be used for archiving and other tasks that are not supposed to run automatically. I propose to implement this as a Pro feature (requiring a quickFilters Pro license) as it is useful and we need to raise funds for the Thunderbird 78 conversion.

**Comment by RealRaven2000** [comment]
Here is a first test version (not localized yet, and not yet disabled without the license validation). Configure via the quickFilters Settings / qF Pro tab in the "Premium features" settings:

![image](https://user-images.githubusercontent.com/6314674/79069141-c42d6e00-7cc3-11ea-85a0-4fee7235ab20.png)

[quickFilters-wx-4.4pre16.zip](https://github.com/RealRaven2000/quickFilters/files/4466339/quickFilters-wx-4.4pre16.zip)

_test version above - please extract the xpi to a file first then drag the file into Add-ons Manager. github does not support attaching Add-ons directly._

**Comment by RealRaven2000** [comment]
To see a list of current shortcuts which are enabled by default in Thunderbird, please check:
https://support.mozilla.org/en-US/kb/keyboard-shortcuts

**Comment by pdqpat** [comment]
I checked both keyboard shortcuts (folder and selected email); created a new subfolder; created a filter (from/to Axel moves to inbox > quickFilter)
Shft+R and Shft+F did not move any email,
Buttons for both functions produced popup windows (screenshots) which eventually disappeared. Did not move any email.  (I did not test the buttons before I installed this test - sorry)
Win10 home v1909 b18363.720  - Thunderbird 68.7.0 32bit

![Run on folder](https://user-images.githubusercontent.com/5642804/79078139-49b91a00-7cd4-11ea-92e9-25c79c0d4a77.jpg)
![Apply to selected messages](https://user-images.githubusercontent.com/5642804/79078141-4a51b080-7cd4-11ea-88ee-3f6d149eacfe.jpg)

**Comment by pdqpat** [comment]
Just trying odd things, I dragged an email to you manually into the _quickFilter_ subfolder, then dragged it back into _inbox_.  It moved back to the subfolder **by itself**...

**Comment by RealRaven2000** [comment]
> Just trying odd things, I dragged an email to you manually into the _quickFilter_ subfolder, then dragged it back into _inbox_. It moved back to the subfolder **by itself**...
> Ctrl+Z did nothing. Right-click "move back to inbox" did nothing.

You have told the assistant to do that automatically - by default is does the move when new mail arrives in the inbox. Since you do not want this I suggest the following:

1) edit the filter like this:
Apply filter when: 
[x] Manually Run: enabled
[ ] Getting new Mail: disabled
![image](https://user-images.githubusercontent.com/6314674/79078952-c8797b80-7d03-11ea-84a3-62fa578ec064.png)

if you like you can set these as defaults for new filters in quickFilters settings / _New Filter Properties_ (just right-click the assistant button to get there quickly):
![image](https://user-images.githubusercontent.com/6314674/79078967-f5c62980-7d03-11ea-9d4c-56b35424c734.png)

**Comment by pdqpat** [comment]
I had set it to _run manually_ and _When archiving._
![Options manual +Archive](https://user-images.githubusercontent.com/5642804/79079234-e337fa00-7cdb-11ea-82f1-9a59022974c9.jpg)

**Comment by RealRaven2000** [comment]
Implemented in 4.4 published on 09/06/2020
