### ISSUE TITLE
View Filters icon missing from message bar

### ISSUE THREAD

**Issue by SKelem** [RealRaven2000/quickFilters#127]
The folder toolbar seems to have changed. It looks like:
[toolbar screenshot](https://www.linkpicture.com/q/toolbar-2022-08-20.png)
It's missing the button for opening the list of filters. Is there a way to bring it back? Is there a different way to open that window?

Thanks,
Steve Kelem

**Comment by RealRaven2000** [comment]
yes, you have to configure it from quickFilters advanced options:

![image](https://user-images.githubusercontent.com/6314674/188513322-0f403164-ba05-420e-93fb-0b16a87e4a96.png)

result:

![image](https://user-images.githubusercontent.com/6314674/188513389-751581f1-2fd7-460d-905d-3036ae317d5a.png)

Screenshots were made in Thunderbird 102.1 in Windows 10 (I finally got around to upgrading my development PC from Windows 7) - by the way you can paste images directly into github.

**Comment by RealRaven2000** [comment]
This may be cause by interaction with QuickFolders, and I have come up with a solution in issue #129. You will need to install both a new version of quickFilters (5.6) and QuickFolders (5.14) for the fix to work.
