### ISSUE TITLE
quickFilters Asssitant stopped working

### ISSUE THREAD

**Issue by MichiFr** [RealRaven2000/quickFilters#136]
Hi Axel!

Just noticed that quickFilters **Assistant** stopped working here. Using TB version 102.5.0 and qfa version 5.6, licensed. Don't know with which TB version the assistant stopped since I'm not using it regularly.

When clicking on the toolbar button the envelope icon turns red, however there is no popup nor any further reaction.

The error console does not show any error while execution the button. 

It does not matter if I'm focusing any message nor in which folder I'm in when clicking the button.

There is not window opening in the background as far as I can see in Windows (Win 10 x64) task manager or when switching between running apps.

I'm using a three column layout in TB, if that matters. However, when switching to a different layout there is no qfa toolbar either.

Can you please assist?

**Comment by RealRaven2000** [comment]
> Just noticed that quickFilters **Assistant** stopped working here. Using TB version 102.5.0 and qfa version 5.6, licensed. Don't know with which TB version the assistant stopped since I'm not using it regularly.
> 
> When clicking on the toolbar button the envelope icon turns red, however there is no popup nor any further reaction.

Once the envelope turns red, can you move/copy emails or tag emails? This should bring up the assistant. Likewise, if you right-click any existing message and select "_quickFilters: Create Filter from Message_"

![image](https://user-images.githubusercontent.com/6314674/202693520-c8105a14-79e4-46ce-937a-481e74995b0f.png)


One thing to note is that enabling the assistant will not display a messagebox - the _notification panel_ on the bottom that turns up with "factory settings" can be permanently disabled:

![image](https://user-images.githubusercontent.com/6314674/202693249-9cee6f6b-794a-41d0-aad1-2d92f68ceaf5.png)

**Comment by MichiFr** [comment]
**Ah yes, sorry my bad - you are correct!** 

I could bet when pressing the button in any previous release, the assistant started itself. 
I do not mind however, if it comes up only when moving or copying any message or using the context menu.

Thanks for the fast reply and have a nice day!

Michael

**Comment by RealRaven2000** [comment]
> **Ah yes, sorry my bad - you are correct!**
> 
> I could bet when pressing the button in any previous release, the assistant started itself. I do not mind however, if it comes up only when moving or copying any message or using the context menu.

no worries! It would have to base the new filter on the current message, which is what the context menu command is for. I think having it triggered by the manual moving of mails is a nicer shortcuts that extracts information on an action you would have done anyway to automate it...

The reason the naked filter editor dialog is so clunky is that it doesn't make any assumptions / automations, so it cannot auto-fill anything related to search terms / filter actions - which are so cumbersome to fill in manually.
