### ISSUE TITLE
Assistant triggered when emails are deleted (quickFilters 5.7)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#142]
When the assistant is active, deleting emails triggers it and prompts to create new filters. This behavior is unintended.

**Comment by RealRaven2000** [comment]
I moved this issue to the quickFilters repository (I had accidentally added it to my Add-on FiltaQuilla) - sorry about the noise.

**Comment by hartholzpirat** [comment]
Thank you everything worked

**Comment by RealRaven2000** [comment]
> Thank you everything worked

I have another HUGE problem. When filters are triggered automatically (or when I run them via the run filters on selected messages) this also invokes the assistant on my production profile. This is extremely problematic, as I cannot tell in the folder listener that checks for moved / copied messages _what_ invoked the function. I need to open another bug for this one, if it doesn't work out I may have to roll back all the changes from the change set to "Remove monkey patch code for Tb move mail commands". This is going to get ugly... will raise a separate issue for it

**Comment by RealRaven2000** [comment]
Fixed in 5.7.1 - Published 26/Dec/2022

**Comment by RealRaven2000** [comment]
Please refer to #145 for changes relating to delete / archiving
