### ISSUE TITLE
Request for putting Github Link in Support Tab

### ISSUE THREAD

**Issue by PotatoCarl** [RealRaven2000/quickFilters#146]
Hi
I have been required in the past (for good reasons, too) to paste bug regports on the Github pages instead of mailing the author directly.
However, I noticed that instead of the GitHub Page, only the "direct email" option in the support-tab of quickFilters is listed.
For a better compliance, I suggest to put the GitHub pages at last additionally on the support page, as I myself tend to forget about it and rather use the "support" options, i.e. directly mailing the author.

And a healthy and happy New Year to you all!

**Comment by RealRaven2000** [comment]
Good idea, it can be done easily enough. I think my other Add-ons  (QuickFolders, SmartTemplates) direct to an interstitial page on quickfolders.org, but I was thinking about pointing them to github directly as well).

**Comment by RealRaven2000** [comment]
New version with butto ;eading to Github, here:

[quickFilters-wx-5.7.2pre41.zip](https://github.com/RealRaven2000/quickFilters/files/10385684/quickFilters-wx-5.7.2pre41.zip)

**Comment by RealRaven2000** [comment]
Implemented in 5.8, released on 15/02/2023
