### ISSUE TITLE
How do you copy filters between accounts

### ISSUE THREAD

**Issue by fakeologist** [RealRaven2000/quickFilters#15]
I have 5 email accounts, and I want the filters to run on ALL of them.
How do I do this?

**Comment by RealRaven2000** [comment]
You have to copy them to the other account(s). Highlight the mails, then click the copy button:

![image](https://user-images.githubusercontent.com/6314674/85279869-08d14480-b47f-11ea-8450-3d18f82ab463.png)

then
1) select the target account
2) select a position in the list
3) press the paste button
![image](https://user-images.githubusercontent.com/6314674/85279980-33bb9880-b47f-11ea-88bb-5822458ca41f.png)

repeat all steps (including copying) for each account. This doesn't actually use the clipboard but it is 100% internal to Thunderbird.

Another way would be to use backup on one account and then loading the filters using restore button on the target account (but that gives you less control on where and how many you transfer)
![image](https://user-images.githubusercontent.com/6314674/85280209-96149900-b47f-11ea-804d-668099e7d82a.png)

It's probably a good idea to make a backup anyway before you do big changes like this.

**Comment by fakeologist** [comment]
Thanks
