### ISSUE TITLE
Only Apply a Particular Filter to Read Messages (ie, Not New or Unread)

### ISSUE THREAD

**Issue by EnigmaSolved** [RealRaven2000/quickFilters#156]
I'm either missing something, or maybe there is a bug. I have a filter with the following parameters:

- Manually Run
- Match all of the following
- From ends with @example.com
- Status isn't New (also tried: Status is Read)

What I'm aiming for is that I have some messages which I want to review, and which I sometimes want to leave in my Inbox for a while, so I would like for these, if they are kept as New/Unread to not get moved by the filter, but I can't seem to figure out how to get that to work (and I would prefer to base it off of New/Unread as opposed to Starred). Every time I manually run the above filter (either variation) on a test message it moves the message even though the message is New/Unread.

I'm on QuickFilters Pro 4.5
Thunderbird 68.3.1

Thanks in advance for any help/guidance! :)

**Comment by RealRaven2000** [comment]
I am actually working on new functions that will only be available from Thunderbird 91 onwards, also working on compatibility with Thunderbird 110.b4, there will be a lot of changes in this years ESR 115. Haven't really ran legacy versions for a long time, so I can't really test on that system right now.

to leave emails remaining in your inbox for a while you could use the search term "age in days > 30 days" or something along those lines; and then hit the run filters on folder button once in a while.

**Comment by EnigmaSolved** [comment]
Yeah, I totally do need to upgrade, and I absolutely understand you can't give energy to supporting a legacy version. Can you tell me, though, would the filter(s) I described in my original post work on current versions of QuickFilters (ie, on current versions of Thunderbird), and if not, is that something likely to get worked on / fixed / implemented eventually?

Your proposed workaround is clever and appreciated (and may be suitable for some of my use-cases), but I'm still interested in the original angle too.

**Comment by RealRaven2000** [comment]
This works for me *(testing on Thunderbird 102.7.2):

![image](https://user-images.githubusercontent.com/6314674/218316707-16f17efc-196e-4c7f-a0a6-d12a4c1c9adb.png)

The unread messages are not moved by this filter.

**Comment by EnigmaSolved** [comment]
I guess we should consider this Closed then, as it sounds like what I'm wanting works on current versions. Thanks much! :)
