### ISSUE TITLE
prolonged license but didn't get new key

### ISSUE THREAD

**Issue by RalfRoemling** [RealRaven2000/quickFilters#168]
After my license expired I bought the new one. 

Money is already withdrawn but I didn't get the license or any invoice from Fastspring as last year.

**Comment by RealRaven2000** [comment]
Dear Ralf, can you please contact me directly (axel.grude@gmail.com) so I can send you the key?

**Comment by RealRaven2000** [comment]
I found it - will send you details directly, hope it doesn't end up in Spam.
