### ISSUE TITLE
Gruppierte Ordner scrollt automatisch zurück zum Posteingang

### ISSUE THREAD

**Issue by tom1stein** [RealRaven2000/quickFilters#17]
Immer, wenn quickFilters aktiviert wird,  scrollt die Liste "Gruppierte Ordner" regelmäßig hoch zum Posteingang. Dieses Scrollen passiert in der 3-Spalten-Ansicht, wenn eine Mail in der Vorschau angezeigt wird, alle paar Sekunden von selbst. Natürlich fällt dies nur auf, wenn es mehr Ordner gibt, als auf einen Bildschirm passen und einer der unteren Ordner angewählt werden soll. Ohne Voranzeige passiert es nur immer dann, wenn man eine Aktion (z.B. ins Menü klicken) auslöst. Wenn man also eine Mail weit unten in der Ordnerliste links einsortieren will, dorthin scrollt, dann die Mail anfassen will - ist der links angezeigte Ordner wieder weg und der oberste Ordner Posteingang ist markiert. Das ist sehr nervig, wenn man weiter unten Mails einsortieren will. Das Verhalten hört auf, sobald der quickFilters Assistent deaktiviert wird.
![cjfmpgohhkhnjiim](https://user-images.githubusercontent.com/42583041/85931120-388aad00-b8c2-11ea-86e8-6e4f3fd8d9f9.png)

**Comment by RealRaven2000** [comment]
ich markiere das mal als bug.

wahrscheinlich habe ich das Problem nie so mitgekriegt, weil ich

- keine Gruppierten Ordner benutze
- trotz über 300 Verzeichnisse grundsätzlich nicht den verzeichnisbaum zum navigieren / mails verschieben nutze. Dafür benutze ich ausschliesslich QuickFolders. Die Zeit ist mir einfach zu Schade um den ganzen Tag in einer Listbox rumzuscrollen.

**Comment by tom1stein** [comment]
Ein Szenario von Quickfilters ist, dass man nur noch einmal manuell den richtigen Ordner anlernt. Und genau dann schlägt diese Aktualisierung der Ordnerliste zu.

**Comment by RealRaven2000** [comment]
> Ein Szenario von Quickfilters ist, dass man nur noch einmal manuell den richtigen Ordner anlernt. Und genau dann schlägt diese Aktualisierung der Ordnerliste zu.

was heisst _"dass man nur noch einmal manuell den richtigen Ordner anlernt"_? Ich bin mir nicht ganz sicher was das heisst, kannst Du grob die Schritte beschreiben

**Comment by tom1stein** [comment]
Ein Szenario, um quickFilters eine neue Regel beizubringen, ist, es per Button zu aktivieren und dann eine Mail per Drag&Drop in den gewünschten Zielordner zu verschieben. quickFilters merkt sich so Absender, Betreff, Zielordner etc., diese Daten kann man ggf. noch manuell anpassen. Man schaltet also den quickFilters-Lernmodus per Button ein, scrollt ein letztes mal zu dem gesuchten Zielordner, damit dieser in der Ordnerliste sichtbar ist, und will die Mail nun per Drag&Drop dahin ziehen. Aber spätestens beim Anklicken der Mail (teilweise auch alle paar Sekunden von selbst) scrollt die Ordnerliste zurück nach oben, wenn quickFilters über den Button im Lernmodus aktiv ist.

**Comment by RealRaven2000** [comment]
ok. also mit dem quickFilters Assistenten (standard Szenario) - sind noch andere Add-ons installiert? Ist es vielleicht auch an neu ankommender Email im Eingangsverzeichnis verknuepft? oder in neue Emails die waehrenddessen automatisch in andere Verzeichnisse verschoben wurden?

**Comment by RealRaven2000** [comment]
quickFilters scrollt nicht im Verzeichnisbaum. Ich empfehle QuickFolders und den "quickMove" Befehl fuer einfacheres verschieben ohne den Baum, Nostalgy waere auch noch eine Moeglichkeit.
