### ISSUE TITLE
missing icon on QF Current Folder Bar (Linux, Thunderbird 102.9.1)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#172]
2 users reported this independently. On Linux the additional quickFilters buttons for running filters are not displayed any more on the QuickFolders Current Folder toobar:

Expected:
![image](https://user-images.githubusercontent.com/6314674/229180909-13cdd522-7dc9-4f14-94ec-f789b13dd1b5.png)

Observed:
![lC1UUmYQluePsbwM](https://user-images.githubusercontent.com/6314674/229181018-29a1e26b-5f29-45e8-9146-a5c672cf9231.png)

Configuration is on the quickFilters settings Advanced page:

![image](https://user-images.githubusercontent.com/6314674/229181251-ecc39e58-15ad-4c9a-8862-c47a55ac7ffa.png)

I suspect it is an issue with Linux-specific changes to the Thunderbird style sheet

**Comment by alfredomuchacho** [comment]
I have the same problem: since the update to Thunderbird 102.9.1 the icons on the toolbar are missing. I use Manjaro.

![2023-03-31-15-17_clipbord_image](https://user-images.githubusercontent.com/97470836/229267915-f771440d-88bb-4fda-a229-1a644b8ce474.png)

The configuration of QuickFilters is as follows:

![2023-04-01-07-42_clipbord_image](https://user-images.githubusercontent.com/97470836/229267928-96f23238-c750-4241-ae07-4a534e905110.png)

**Comment by RealRaven2000** [comment]
thanks for the screenshots. You can check the button's css properties using inspector (Ctrl+Shift+I) - I suspect it is added by quickFilters but a Linux-specific CSS rule prevents it from being displayed. I will have to make a new LInux VM to test this, or ask a friend on the next dev call (Thursday evening).

It is probably a CSS display issue. I would investigate it with the built in inspector - the debugger and css inspector are in Tools / Developer Tools / Developer Toolbox.

(Or use the shortcut Ctrl+Shift+I) - this launches a remote debugger.

The first place I would look is in the "Inspector" tab:

1 select inspector
2 select the inspect tool
3 click on a button close to the missing button:

![image](https://user-images.githubusercontent.com/6314674/229286203-8a30b223-2d44-4e8e-ba42-b85f8be5dbda.png)

If you can find the button "quickfilters-current-runbutton" = check under the Rules tab, and filter for the "display" rule:

![image](https://user-images.githubusercontent.com/6314674/229286245-c4ba10bc-9dac-46fb-a103-667075c8988c.png)

To see the Thunderbird built in styles make sure that you enable Show Browser Styles in settings!

![hmfFmcIb9UyLiyJv](https://user-images.githubusercontent.com/6314674/229286255-4673e783-edcb-4589-a5c3-5dcc3c380e75.png)

![tnbTg7A0qQKcPhr3](https://user-images.githubusercontent.com/6314674/229286263-3d50aa27-cee2-423b-abf2-e080df6a5c93.png)

If there are multiple rules you can see which one "wins" on the  "Computed" tab:

![iKwg1OOjmm7IUCPx](https://user-images.githubusercontent.com/6314674/229286296-4f102410-8ebc-4c32-a332-be9d034705c5.png)

**Comment by alfredomuchacho** [comment]
I'll get back to you about the problem. Even if I integrate a button of QuickFilters in the central bar, I see the icon, but the button does not work. I can only access the filters via "Tools" --> "Filters" of Thunderbird. No learning mode or other functions of QuickFilters work. :-(
![2023-04-08-09-56_clipbord_image](https://user-images.githubusercontent.com/97470836/230710570-e1e55f2c-aa91-4e06-ac9b-9822ae64c920.png)

**Comment by RealRaven2000** [comment]
> I'll get back to you about the problem. Even if I integrate a button of QuickFilters in the central bar, I see the icon, but the button does not work. I can only access the filters via "Tools" --> "Filters" of Thunderbird. No learning mode or other functions of QuickFilters work. :-( ![2023-04-08-09-56_clipbord_image](https://user-images.githubusercontent.com/97470836/230710570-e1e55f2c-aa91-4e06-ac9b-9822ae64c920.png)

When you add the button, the event handler isn't added at that time, only when the Add-on starts (this means you have to restart Thunderbird after adding the button) - I  am working on a fix at issue #175 - if you don't want to restart Tb after adding a button, please try the new version linked there.

**Comment by RealRaven2000** [comment]
I finally managed to install an Ubuntu image using Windows 10 Hyper-V, and oh boy was this painful. Cost me about 3 hours. I think I going to go back to Virtualbox as soon as I can - I can;t even share folders with this windows BS.

Anyway I found the following error when I started up quickFilters in Thunderbird on  Ubuntu:

TypeError: mnuToolsCreateFromMsg is null qFi-messenger.js:120:3

I currently do not know why this error doesn't happen in Windows - I suspect the (context) menu only exists there

this would lead to part of the script that injects elements into the context menu, I will upload a new version for testing below shortly.

**Comment by RealRaven2000** [comment]
New version (uploading for myself to test in Ubuntu):

[quickFilters-wx-5.9.1pre14.zip](https://github.com/RealRaven2000/quickFilters/files/11183332/quickFilters-wx-5.9.1pre14.zip)

**Comment by alfredomuchacho** [comment]
With today's update of QuickFilters everything works as usual again. All buttons are back, all functions are working again. Thank you very much for your great work. :-)

**Comment by RealRaven2000** [comment]
Fixed in 5.9.1 released on 09/04/2023 (April)
