### ISSUE TITLE
quickFilters 5.9 won't trigger with mail move; changed nothing

### ISSUE THREAD

**Issue by FireScribeFire** [RealRaven2000/quickFilters#174]
Since around the end of last week Quick Filters 5.9 has not been triggering when I've moved mail to a new regular folder. It's like it's turned off. (I have it deselected not to trigger when sent to trash or archive.) I didn't make any changes and hadn't upgraded Thunderbird to V102.9.1 until just now, which didn't change the behavior. I'm on Mac V12.6. 

Any idea what's going on? 

![Screen Shot 2023-04-04 at 15 28 51](https://user-images.githubusercontent.com/125511736/229899789-1ab887e1-3c33-48d7-ac58-0d43428fc0df.png)

**Comment by RealRaven2000** [comment]
Can you switch on debug mode on advanced and take a  glance at the Error console
Thunderbird menu = Tools / developer tools / error console
(Ctrl+Shift+J)

Configuration:

![image](https://user-images.githubusercontent.com/6314674/229943839-225243f8-ac1e-4444-96b7-9ccfef3f86e0.png)

to capture the error log in digestable to clipboard (please no screenshots for the log, we need text only):

![image](https://user-images.githubusercontent.com/6314674/229943922-2da734aa-d706-4c74-b8ce-4e7ea0279912.png)

Could be that your folders have faulty flags (e.g. archive flag set), it should tell in the error log.

**Comment by FireScribeFire** [comment]
services.settings: Failed to load last_modified.json: TypeError: NetworkError when attempting to fetch resource. Utils.jsm:330
WebExtensions: 102.9.1 qFi-messenger.js:15
Cookie “issuem_issue” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite www.flashfictiononline.com
Cookie “issuem_issue” has been rejected because it is already expired. www.flashfictiononline.com
NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI] FaviconLoader.jsm:420
NS_ERROR_MALFORMED_URI: Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService.newURI] FaviconLoader.jsm:420
2147942487
[Exception... "Component returned failure code: 0x805e0006 (NS_ERROR_CONTENT_BLOCKED) [nsIChannel.asyncOpen]"  nsresult: "0x805e0006 (NS_ERROR_CONTENT_BLOCKED)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: load :: line 191"  data: no] FaviconLoader.jsm:191:20
2147942487
quickFilters [logTime init]
loadPreferences - start:
quickFilters 20:25:14.258  [0 ms]   
Adding 39 preferences to Preferences loader…
quickFilters 20:25:14.259  [1 ms]   
loadPreferences - finished.
quickFilters 20:25:14.469  [210 ms]   
Version() getter. addonInfo:
quickFilters 20:25:16.489  [2020 ms]   
Tab Select: quickFilters-Panels selected panel = quickFilters-Options-Advanced

**Comment by RealRaven2000** [comment]
I just see you have automatic start of assistant mode configured - is the button red (assistant active)? what happens if you switch it off and on manually?

**Comment by RealRaven2000** [comment]
> I just see you have automatic start of assistant mode configured - is the button red (assistant active)? what happens if you switch it off and on manually?

I did a quick sanity test this morning, automatic starting appears to work here as well:

![image](https://user-images.githubusercontent.com/6314674/230040564-8678c8a5-3de6-4dbf-b3aa-2ebf499f7d41.png)

Can you run the test again, but enable the following additional settings (via Debug / right-click). Go to quickFilters settings, advanced page and right-click the _debug mode_ setting.

![image](https://user-images.githubusercontent.com/6314674/230041672-181a47cb-72d4-4d59-bb10-518f730ad3b9.png)


```
extensions.quickfilters.debug.assistant = true	
extensions.quickfilters.debug.createFilter = true	
extensions.quickfilters.debug.dnd = true	
extensions.quickfilters.debug.events = true	
extensions.quickfilters.debug.filters = true	
extensions.quickfilters.debug.getSourceFolder = true	
extensions.quickfilters.debug.msgMove = true
```

![image](https://user-images.githubusercontent.com/6314674/230041080-a064b7fa-dd94-438e-8866-74a32148cd26.png)

You may reset the debug log _before_ you drag / move an email:

![image](https://user-images.githubusercontent.com/6314674/230041953-eb8e1c45-2bdd-4b44-a2f0-15c2103f59cf.png)

**Comment by FireScribeFire** [comment]
The button is not red because my userChrome file makes all my icons the same color and I guess overrides the extension's color changes. When I click it and try to activate the filters, it will not engage. 

I'm not sure where to find: 
extensions.quickfilters.debug.assistant = true	
extensions.quickfilters.debug.createFilter = true	
extensions.quickfilters.debug.dnd = true	
extensions.quickfilters.debug.events = true	
extensions.quickfilters.debug.filters = true	
extensions.quickfilters.debug.getSourceFolder = true	
extensions.quickfilters.debug.msgMove = true

I cleared the console and ran the test again. Here are the results. Incidentally, closing and restarting the browser does not get it working and TB's Config Editor says the installed version is 5.8.1, not the 5.9 the extension says it is. 

about:preferences : Unable to run script because scripts are blocked internally.
Relative positioning of table rows and row groups is now supported. This site may need to be updated because it may depend on this feature having no effect. preferences.js:279:2
quickFilters [logTime init]
loadPreferences - start:
quickFilters 14:0:7.290  [0 ms]   
Adding 39 preferences to Preferences loader…
quickFilters 14:0:7.291  [1 ms]   
loadPreferences - finished.
quickFilters 14:0:7.448  [157 ms]   
Version() getter. addonInfo:
quickFilters 14:0:29.236  [21788 ms]   
Tab Select: quickFilters-Panels selected panel = quickFilters-Options-Advanced
quickFilters [logTime init]
loadPreferences - start:
quickFilters 14:0:45.709  [0 ms]   
Adding 39 preferences to Preferences loader…
quickFilters 14:0:45.711  [2 ms]   
loadPreferences - finished.
quickFilters 14:0:45.820  [109 ms]   
Version() getter. addonInfo:


Thanks for trying to help me figure this out. I'd like this to work again. You never know how much you rely on something until it stops working.

**Comment by RealRaven2000** [comment]
> The button is not red because my userChrome file makes all my icons the same color and I guess overrides the extension's color changes. When I click it and try to activate the filters, it will not engage.

With the new interface you will see that the submenu changes, from start filters assistant to end filter assistant:

![image](https://user-images.githubusercontent.com/6314674/230187628-f2319d21-79b9-4b3d-ac57-2ff9de196e8f.png)

![image](https://user-images.githubusercontent.com/6314674/230187555-c951f6db-567f-4c18-9c46-6390af4e1338.png)

what does it show in your case?

> I'm not sure where to find: extensions.quickfilters.debug.assistant = true 

Like I said in the quickFilters advanced settings page. You need to **right-click** the debug mode checkbox:

![image](https://user-images.githubusercontent.com/6314674/230188486-55cc3448-5c02-4b33-a3d0-de70ab016c3b.png)

> 
> I cleared the console and ran the test again. Here are the results. Incidentally, closing and restarting the browser does not get it working and TB's Config Editor says the installed version is 5.8.1, not the 5.9 the extension says it is.

hmm, that is strange - it is written when the Add-on starts up. Just do another run with the above settings enabled.

**Comment by FireScribeFire** [comment]
Man. RIGHT click. Ugh. It's been a day. I called it up and didn't change anything. I did change on the Advanced tab the Advanced Templates. Reply-To and custom templates were deselected. Once I selected them and restarted, it began to work again. 

I'm not sure why it was fine and then wasn't when I hadn't been in any settings, even for TB, but it's working and that's all that matters. Thank you very much. Unless there is anything else you want to check, I'd consider this issue resolved.

**Comment by RealRaven2000** [comment]
> Man. RIGHT click. Ugh. It's been a day. I called it up and didn't change anything. I did change on the Advanced tab the Advanced Templates. Reply-To and custom templates were deselected. Once I selected them and restarted, it began to work again.
> 
> I'm not sure why it was fine and then wasn't when I hadn't been in any settings, even for TB, but it's working and that's all that matters. Thank you very much. Unless there is anything else you want to check, I'd consider this issue resolved.

hmm, that is a strange one - I wonder if there is some intialisation error on the assistant that is connected to Custom templates. Did you create Custom filter templates before? One thing I can imagine (maybe) that qF remembered the last (custom) template and tries to select it. I might have to add some additional error log entries in another trial version to test this, haven't looked at this part of code in a while.

**Comment by FireScribeFire** [comment]
I've never created custom templates and I rarely mess with the filter settings. I predominantly use it to set filters when moving mail. The last thing I did in settings was in February when I changed it to stop triggering the filter assist when moving mail to trash and archives.
