### ISSUE TITLE
Reduce Clicks User Interface

### ISSUE THREAD

**Issue by tracyphasespace** [RealRaven2000/quickFilters#18]
Would it be possible to set it so that it defaults to the filter instead of having to select it, so that instead of 3+ clicks
Select Drag to Junk
Filter Opens
Select Filter
Click Edit or Cancel (Unsure if Cancel actually cancels remembering the addition of the filter content)
Opens edit, click run, 
click close

Should be:
Drag to Junk
Click OK

**Comment by RealRaven2000** [comment]
You can at least save a few of the clicks:

![image](https://user-images.githubusercontent.com/6314674/86187213-2ebbb080-bb33-11ea-944e-e285031f6762.png)

Uncheck the option "open filter editor"

Check the options "automatically select merge" and "Skip to template step"

**Comment by RealRaven2000** [comment]
I believe the OP had a chance to review my reply (even if they didn't follow up) - so I am closing this issue for now. If you want additional functionality after having tried my suggestions, feel free to reopen this issue!
