### ISSUE TITLE
Please add delay to the quickfilter rules

### ISSUE THREAD

**Issue by molitar** [RealRaven2000/quickFilters#186]
As I have 5 email accounts and one gets a lot of emails every single time I open up Thunderbird I get an error that the rules could not be run as it's busy.  If you notice in Microsoft Outlook the filter rules do not run until download finishes to prevent this problem.  Is it possible to put say a 1 minute delay before running the filter rules to help prevent this happening every single time I open Thunderbird?

**Comment by RealRaven2000** [comment]
Running the filters (on startup) is actually something done by Thunderbird, I don't think I can delay that using the Add-on.

I can try ask on the matrix community chat if somebody knows: https://matrix.to/#/#thunderbird:mozilla.org

if the actual moving of the email fails, you might running [FiltaQuilla](https://addons.thunderbird.net/en-US/thunderbird/addon/filtaquilla/?src=ss) with the additional action "move later":
![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/dde5923b-62c8-4293-b53a-8d0d1c72fe3d)

**Comment by molitar** [comment]
So your saying to install FiltaQuilla and see if that move later will help?

**Comment by molitar** [comment]
Hi RealRaven2000, It looks like that may have worked I had over 70 emails on one of my emails and nearly 40 on another email.  Did not get the error message about moving emails.

**Comment by RealRaven2000** [comment]
thanks for closing this off, hopefully FIltaQuilla does what you need. We might look into having "Move later" as a the default action for all filter templates as a special option maybe?
