### ISSUE TITLE
Quick Filters icons not appearing when TB opens in 2 or more windows

### ISSUE THREAD

**Issue by BaliDave** [RealRaven2000/quickFilters#19]
Recently I'm often not getting the Quick Filters icons in the bar above.  I did get it to show up in one window (I generally have 2 TB windows open) by disabling and re-enabling it, but it's not appearing in the other -- see attached.
![QFltrs](https://user-images.githubusercontent.com/3304532/87747867-00beb780-c827-11ea-8ddf-ef95ce75ad7d.jpg)
Also if I close the window without the icons and then reopen it from the remaining, the icons are now showing in both.  I generally start TB with 2 windows open.

You (Axel) answered my email with:

> I am afraid QF isn't well tested for this use case - while in theory it should work as every Window has its own global variables, some of my7 routines use "marshalling" to the main window, by determining the window using "getLastUsedWindow" for that type (3pane) - which may lead to one window being "orphaned". The reason for this is mainly because you can have child windows (such as the QF Options dialog) that need to communicate with the main one.

So it's a bit of a design flaw - I use mail tabs in the one 3pane window instead - QF works well with this and Thunderbird remembers all opened tabs in a session (so you could have one tab for work and one for friends) - on top of that QF stores the currently selected QF tab category for each tab.

For example - I have a set of QF tabs for my day to day work, they are in the category "daily":

then I may open a separate Thunderbird tab and switch over to the category "Friends":

 

QF will keep the selected tabs consistent with the currently open Thunderbird tab.

Having said that, please feel free to file a bug report for this problem:

https://github.com/RealRaven2000/quickfolders/issues

Please click the New Issue button once you're there. This is the best way of tracking (and eventually fixing) this problem. I am currently very busy rewrting Thunderbird as a "mail experiment" so that we can deploy it on Thunderbird 78 - in fact I am paying another developer toi help with this task. I will try and incorporate a solution for this problem while we're at it.

kind regards,
  Axel

Thanks for all your efforts and good work!

**Comment by RealRaven2000** [comment]
Closing for now, I think it should be resolved in 115 at least
