### ISSUE TITLE
Registration Missing

### ISSUE THREAD

**Issue by AndrewMStein** [RealRaven2000/quickFilters#190]
I've written two emails with no response about my paid renewal to Quickfilters. I never got an upgrade code and I keep getting messsages about my licence being expired. I even sent the Amex receipt to show tht it was paid.

**Comment by RealRaven2000** [comment]
I see an order `QUI230330-1533-41111` under your name from Australia on 30/03/2023, is that the one? 

I haven't found any recent communications from you in my Spam folder.

I did a global search based on your name in my emails and found that I had replied to them on 31/03 and 03/04; if you reached out to me around end of march / beginning of April, then it is possible that my Email address (`axel[dot]grude@gmail[dot]com`) is blocked on your mail server. Can you confirm that this is the date when you renewed the license, then I will try to contact you from my alternative email address `thunderbirddaily@gmail[dot]com`.

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/068c6559-b872-452d-86b0-3b59f01b7552)

**Comment by AndrewMStein** [comment]
I found the rogue filter that was trading renewal messages. you should be able to send the emails to me now.

**Comment by RealRaven2000** [comment]
> I found the rogue filter that was trading renewal messages. you should be able to send the emails to me now.

OK, I can resend - I assume you are the same (Australian) user as in my previous screenshot ( ? )

**Comment by RealRaven2000** [comment]
> I found the rogue filter that was trading renewal messages. you should be able to send the emails to me now.

I resent you a new license!
