### ISSUE TITLE
Unable to import/restore filters

### ISSUE THREAD

**Issue by Amoeba00** [RealRaven2000/quickFilters#195]
Moving from a different computer running a version pre 115.  I have the filters exported, but when I select the .json file to import - nothing happens.  Remains blank.  

Does the import work if Thunderbird is in the process of downloading messages (in this case all of them via IMAP)?
Am I missing a step?  Does the filename have to be something specific?

**Comment by Amoeba00** [comment]
Strange - I moved the location of the IMAP mail on my computer and then it all appeared (along with a lot of restarts).  I doubt I'll be able to recreate this error - but all is working now - please disregard.

**Comment by RealRaven2000** [comment]
This could also follow from issue #197 - storage is broken at the moment on the new version.
