### ISSUE TITLE
Where is the Filter Log?

### ISSUE THREAD

**Issue by Amoeba00** [RealRaven2000/quickFilters#198]
I have enabled the "Filter Log" - but where is it?  Shouldn't there also be a place to view the log?  The only option I have is to clear the log, but I don't think that does anything because nothing is appearing.

![image](https://github.com/RealRaven2000/quickFilters/assets/39176113/a870de75-6c21-49ce-bc56-2180c0cb5358)

**Comment by RealRaven2000** [comment]
> I have enabled the "Filter Log" - but where is it? Shouldn't there also be a place to view the log? The only option I have is to clear the log, but I don't think that does anything because nothing is appearing.

in the same window - it's shown once you click on the "Filter Log" button. You just haven't got any data in there yet. There is one log file per account.

By the way, if you know that a mail was filtered falsely to a particular folder, you can find the filters that move mail there, across all accounts using the "find filters" feature:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/af15e547-5a17-42d8-a5e7-650b1d8736f2)

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/b0102346-0588-450f-997f-06b20cc526e4)

(It also used to be a context menu entry in the folder tree, but I haven't ported that for 115 yet)

**Comment by Amoeba00** [comment]
Hmm - ok then it's not working - because emails are definitely being filtered and there is no log.

**Comment by RealRaven2000** [comment]
> Hmm - ok then it's not working - because emails are definitely being filtered and there is no log.

then you found a bug in Thunderbird 115 :) it's a core service - quickFilters is not involved.

**Comment by Amoeba00** [comment]
> then you found a bug in Thunderbird 115 :) it's a core service - quickFilters is not involved.

Ahhh :shit:

**Comment by RealRaven2000** [comment]
closing to declutter!
