### ISSUE TITLE
Remember Copied filters List to insert to other Accounts multiple times

### ISSUE THREAD

**Issue by Justice-Central** [RealRaven2000/quickFilters#20]
I have 8 different Email accounts.  Some filters are unique to a  particular account.  But most filters I need to be GLOBAL so I can write just one filter and have it apply to all 8 accounts.

Thunderbird has no way to do this -- even with the 'Quick Filters' add-on.

I do see where I can copy & paste a particular filter manually into each account's filter list.  But it's very labor intensive because -- unlike all other Windows programs and Windows' default function -- the Quick Filter program does not retain a memory of the copied filter AFTER it is pasted -- so I have to copy it again and again after each paste.  Windows' default function in Explorer remembers the copied file(s) and allows for an unlimited number of pastes after the file(s) are copied just once.

Since Thunderbird has no GLOBAL filter ability  --  Quick Filters stands as a vitally important program for at least allowing users to 'copy & paste' Thunderbird filters from one account to another.  However, it would be infinitely more user-friendly if the Quick Filters program retained the copied file(s) in memory -- so the user does not have to re-copy the same filter after each and every paste.

REQUEST:  Please revise the Quick Filters program so it will function like every other windows program -- i.e., so it will retain the copy function in memory -- so the user does not have to re-copy the same filter after each and every paste.

Thank you.

**Comment by RealRaven2000** [comment]
So reason number 1 for the paste not being repeatable is the fact that it doesn't actually use the windows clipboard at all - I avoided these additional difficulties and do the copy / cut / paste operations internally within the Thunderbird JS code, without touching any OS specific mechanisms (such as Windows clipboard). That means you cannot use this across 2 Thunderbird instances.

Having said that, there is no reason why it shouldn't work within the same Thunderbird across your multiple accounts. I have flagged this as enhancements and will put it to the top of the queue. Will post test versions here.

**Comment by RealRaven2000** [comment]
Test version (thunderbird 78 only)
[quickFilters-wx-5.2pre85.zip](https://github.com/RealRaven2000/quickFilters/files/6255288/quickFilters-wx-5.2pre85.zip)

To install download zip file and drag into Thunderbird Add-ons Manager. Then open quickFilters settings and enable the following checkbox:

Click on the _Advanced_ Tab
enable [x] _Support pasting filters multiple times_
![image](https://user-images.githubusercontent.com/6314674/113520600-1843f900-958c-11eb-9691-4a58fc6b753a.png)

The feature is only available if you have a quickFilters Pro license.

To do: feature still needs to be translated / localized.

**Comment by RealRaven2000** [comment]
I know this is a bit late, but hope you are still interested in this feature?

**Comment by RealRaven2000** [comment]
Implemented in 5.2 published today
