### ISSUE TITLE
Question:  With logging broken in 115, how can I troubleshoot a filter?

### ISSUE THREAD

**Issue by Amoeba00** [RealRaven2000/quickFilters#200]
Could be an issue with 115, but I have a filter that doesn't work..

![image](https://github.com/RealRaven2000/quickFilters/assets/39176113/a5b0f0d7-406b-40cd-9770-66642d1ebd8e)
changed to this - still not working..

![image](https://github.com/RealRaven2000/quickFilters/assets/39176113/a431a49d-e7ac-469c-9a2b-b64065f22506)

Changed it to ends with - and still nothing..

It's supposed to go to a folder, but it stays in the inbox.  I know this used to work at some point, but just now realized that it's not.
(IMAP Gmail)

Thoughts?  Thanks.

**Comment by RealRaven2000** [comment]
Mayb try to change the operators to “ends with” i have a number of domain filters that work like this. But i usually include the @ in mine.

**Comment by Amoeba00** [comment]
I've done that and still no joy.  I have other rules that run before and after with no @ and it filters just fine. 
So I wound up just deleting the filter entirely and created it from scratch by adding the items back one by one (via drag/drop auto create filter) and it now works.  
(also, it's just from - ends with - domain (no @ ).
