### ISSUE TITLE
Tb115: global keyboard shortcuts for running filters don't work anymore

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#208]
It looks like these events aren't triggered in Thunderbird 115 anymore:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/a83a4818-33db-4c0a-919d-27fde53d95b5)

needs to be fixed  ASAP.

**Comment by RealRaven2000** [comment]
quick fix version below:

[quickFilters-wx-6.2.1pre5.zip](https://github.com/RealRaven2000/quickFilters/files/12398764/quickFilters-wx-6.2.1pre5.zip)

---

To test the version above, download the zip file, drag into Thunderbird Add-ons Manager, do not extract contents or if won't install.

**Comment by csantelmann** [comment]
Thanks for the quick response and the fix! I'll try it at once.

**Comment by csantelmann** [comment]
Now it works like a charm for me! Thanks a lot!

**Comment by RealRaven2000** [comment]
Fixed in 6.2.1 - Published 22/08/2023
