### ISSUE TITLE
filter Databases issues

### ISSUE THREAD

**Issue by terashy88** [RealRaven2000/quickFilters#213]
I'm Trying to Archive a mail and always get this error below, also after untick all setting and deleting my filters

```
Tried to create a filter 7 times, but it didn't work out.
Try to move a different message. Otherwise, updating Thunderbird to a newer version might help.

There seems to be an issue with message Databases not being ready when emails are moved across to a different IMAP account. We currently have a support request with the mail application teams to help us resolve this problem. Alternatively you can use 'Create Filter From Message' on the message after you moved it, or move the mail to a local folder.
```

being on thunderbird 115.2.2-1 Linux

**Comment by RealRaven2000** [comment]
FIrst of all, do you want to create a filter (My guess is you have set your filter assistant to start automatically?). If not, then you can disable the folder listener during archiving here:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/94854a62-0d77-421e-8829-a27000243667)

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/518896a0-5b1a-4a4a-8b0b-6b72e6d755ff)

if you set `extensions.quickfilters.assistant.exclude.archive = true` , you can disable the assistant during archiving. However if you want to generate a filter that archives (following your action based on assistant), then an error log  would be great.

**Comment by RealRaven2000** [comment]
### How to create a debug log (quickFilters)

* Ctrl+Shift+J opens the error console
    
    configure it as follows:
    
    ![C6ifshZ4C3wT0cA9](https://github.com/RealRaven2000/quickFilters/assets/6314674/01c7074d-1b5c-4a78-a873-cd0e8de68d03)
    
* If you need more information from quickFilters you can enable Debug Mode in advanced settings:
    
    ![gKpeMqFNMvHcbzIp](https://github.com/RealRaven2000/quickFilters/assets/6314674/43d303a7-9d78-451b-81df-e98e24002e04)

* On the _Advanced_ tab 1 , activate 2 Debug Mode then right-click it 3 to get additional log options...  

    ![V0P9kjTM1Dl0KgJA](https://github.com/RealRaven2000/quickFilters/assets/6314674/0b6363d9-2309-4b20-9b7c-98dfed831beb)

    
    For creating new filters you could enable the following options:
    
    ![V0P9kjTM1Dl0KgJA](https://github.com/RealRaven2000/quickFilters/assets/6314674/dccc2485-644f-4414-8aa2-b4f8085eb8ed)
    
* Now you're ready for a test - carry out whatever steps you need for reproducing your issue - the log window will fill with messages.
* First, clear the log output.  
      
    ![bjjpgednpnafgnde](https://github.com/RealRaven2000/quickFilters/assets/6314674/5c72b3ce-02d0-4d04-b670-41d7f1454a8b)
    
* Right-click on any message, then select Export visible Messages to Clipboard  
      
   ![X86iWk9WVruLtlV1](https://github.com/RealRaven2000/quickFilters/assets/6314674/b8524c89-d2f4-4696-9603-49810df4fe11)
    
* You can now paste your log results from the clipboard into your reply.

**Comment by terashy88** [comment]
Thanks `extensions.quickfilters.assistant.exclude.archive = true` fix that

**Comment by RealRaven2000** [comment]
ok cool. Remember the default is true so you must have activated it (manually set to false) at some stage... The error should still not show but bring up the assistant to generate a new filter that can archive stuff for you.
