### ISSUE TITLE
does not work at all

### ISSUE THREAD

**Issue by kkivi** [RealRaven2000/quickFilters#22]
After I install filtaQuilla in my Windows 10 Thunderbird 68.12.0 (32-bit)
nothing happens except menu item in addons menu. I marked all checkboxes
in options but didn't get any additional menus, controls, or functionality.
And I feel that thunderbird started to behave in a weird way - not downloading messages until restarted.

**Comment by RealRaven2000** [comment]
could be another Add-on frigging up the tools menu.

It works in my installation.

![image](https://user-images.githubusercontent.com/6314674/92311261-87814c80-efad-11ea-8989-7fdfe35cf76f.png)

are you getting errors in JavaScript console (Ctrl+Shift+J)

**Comment by RealRaven2000** [comment]
did you get any change? I still have no answer to my previous question.

**Comment by RealRaven2000** [comment]
No replies from OP, so I am closing this. I guess it is a FiltaQuilla issue, anyway.
