### ISSUE TITLE
quickfilters does not trigger assistant in Betterbird when Deleting mail

### ISSUE THREAD

**Issue by GoeWink** [RealRaven2000/quickFilters#225]
Since the last upsatge of Betterbird (115.4.2-bb17 (64-Bit)) Quickfilter do not any longer after start the assistent
- recognizew new tag
- - recognize DELETE as the function to move into trash. So it does not open the dialogue for new filter
- - if there is more than 1 tag the filtering do not work (maybe 1 tag to mark, 1 tag for filtering)
- - So without creating a new filter the assistant stay "ON" (I have marked to close after each creating filter...
- On Windows10, Quzickfilters actual.
- I found a ZIP file in the other tread for Betterbird. But this seems to be to old because this removed the Quickfilters buton ans I had to delete and reinstall the add on..

**Comment by RealRaven2000** [comment]
I was using a monkeypatch that overwrites DefaultController, which used to be in charge of loads of commands such as cmd_delete but I see that doesn't appear to be called in this case. Have to find out when it is instantiated and whether there is now a separate one for each tab, and then monkeypatch that / those one by one and also have a method of restoring them when quickFilters is removed / updated / disabled etc.

the difficulty is often to find when and where from the code for global overrides like this can be called.

**Comment by RealRaven2000** [comment]
try the file below. make sure deleting is not exluded in the setting Actions / Assistant should ignore...

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/f6cb33fc-7073-4cbd-8190-9b8d8a274538)

----

[quickFilters-wx-6.4pre50.zip](https://github.com/RealRaven2000/quickFilters/files/14947599/quickFilters-wx-6.4pre50.zip)

To install version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Fixed in 6.4 - Published 11/04/2024
