### ISSUE TITLE
Feature Request: Filter Emails by Specific Header (Content-Type)

### ISSUE THREAD

**Issue by Philipp0205** [RealRaven2000/quickFilters#226]
Hello,

I'm encountering a frequent scenario where I receive numerous meeting invitations via email. I'd like to automatically organize these by moving them to a specific folder.

Currently, I'm considering using the Content-Type header to identify these specific emails. The relevant invitations typically include this header:

`Content-Type: text/calendar; charset="utf-8"; method=REQUEST`

Is there an existing feature in quickFilters that supports filtering based on email headers, specifically the Content-Type? If not, integrating such a feature would greatly enhance email organization for similar use cases.

Thank you!

**Comment by RealRaven2000** [comment]
Any additional filter conditions / search methods can be implemented by my other Add-on FiltaQuilla, so I suggest to open a support request there:

https://github.com/RealRaven2000/FiltaQuilla/issues

once the new method exists, then you can even build a new template in quickFilters settings / advanced:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/03b87f3a-8df5-4e4f-bbcb-fc01372a9dd6)

**Comment by Philipp0205** [comment]
Thanks, will do that :)
