### ISSUE TITLE
Pressing return after setting a filter adds an empty line and closes the window.

### ISSUE THREAD

**Issue by tokyis** [RealRaven2000/quickFilters#240]
Pressing return after setting a filter adds a line and closes the window immediately, running the filter on a folder after this performs the filter actions on all emails since the filter would typically be positive such as `if [field] [contains/ends with/etc] ""` and match everything.

![image](https://github.com/RealRaven2000/quickFilters/assets/6498212/c833978c-281c-469b-bad7-50c8d566bb40)

Running version 6.4 on Thunderbird 115.9.0.

**Comment by RealRaven2000** [comment]
> Pressing return after setting a filter adds a line and closes the window immediately, running the filter on a folder after this performs the filter actions on all emails since the filter would typically be positive such as `if [field] [contains/ends with/etc] ""` and match everything.
> 
> ![image](https://private-user-images.githubusercontent.com/6498212/321819287-c833978c-281c-469b-bad7-50c8d566bb40.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MDczMzksIm5iZiI6MTcxMjkwNzAzOSwicGF0aCI6Ii82NDk4MjEyLzMyMTgxOTI4Ny1jODMzOTc4Yy0yODFjLTQ2OWItYmFkNy01MGM4ZDU2NmJiNDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTJUMDczMDM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTRkY2JlNjE3MzhmNmQ5MDg5YTc1YzkzYjMwNTExZTRhMjAxNjY3MWIxZWZmNzRlZjYzYzhlMzAwNmMxN2EyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.obFJ1832wgC-kqyqf6NxivK5QmnnwpsrpQ4vot5Mb1I)
> 
> Running version 6.4 on Thunderbird 115.9.0.

ok I think you need to post this at bugzilla (for Thunderbird), because that's just the standard behavior of that window, not sure I can change anything from my side here. By the way, in windows dialogs the default Button is usually specially formatted and will always react to [Enter] unless you are in a multiline textbox entry.

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/c80ce0d3-904e-41fe-8d7b-8d81ade101da)

**Comment by RealRaven2000** [comment]
To raise a bug for Thunderbird go to the [Mozilla Bugzilla](https://bugzilla.mozilla.org/home).

Create an account or use an existing account (you can use your Github account) to log in
Click New Bug
Click Thunderbird
IN Categories, select Filters
Click enhancement
Add your description at the bottom

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/e41d630f-1574-494c-bc80-52f4c8fbb03f)

**Comment by tokyis** [comment]
Thank you, I apologize for wasting your time, I raised a [bug for Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1892651).

I've been using your extension for so long that I had forgotten that window was native...

**Comment by RealRaven2000** [comment]
> Thank you, I apologize for wasting your time, I raised a [bug for Thunderbird](https://bugzilla.mozilla.org/show_bug.cgi?id=1892651).

thanks!

> I've been using your extension for so long that I had forgotten that window was native...

no worries, never a waste of time if there is a real bug report at the end of the line! I am hoping that Thunderbird will switch over version control to Github soon, then I will be more motivated to contribute patches (especially around filtering) to the Core team again. their current system is very convoluted and time consuming which makes it hard for casual contributors
