### ISSUE TITLE
Dialog buttons cut off on filter assistant window (Ubuntu 22.04)

### ISSUE THREAD

**Issue by R7914T** [RealRaven2000/quickFilters#243]
I wanted to make a filter  to move items from the inbox  to a specified folder.   I went to the folder, found an appropriate email and tried to create the filter. Just bellow the bottom of the screen are two buttons that are  mainly off screen.  I do not know which button to click  to confirm the filter. I tried to follow a similar query raised here but could not work out the exact instructions for Ubuntu 2204.

**Comment by RealRaven2000** [comment]
Can you add a screenshot please? I did some minor layout fixes in [6.4](../releases/tag/6.4)

This is what the dialog looks like in Windows:
![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/7e04dd1d-5315-48ad-8b69-c098a3c55c89)

- you want to click the left button (which is either NExt or Create Filters, depending on which page of the assistant you are)
- the right-most button is [Cancel]

The window can be resized, but something in the layout makes it have a minimal height - if there is a problem eith vertical space here i could add a button above the header preview area to collapse / show it?

**Comment by RealRaven2000** [comment]
Here is a suggestion on how I could improve the dialog:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/3bed5e50-2eb3-4ee3-bf8f-f1d01e3410fd)

- Add collapse / expand elements beside the description and preview fields
- moved the preview field to the right of the heading **email(s)**
- this is what it would like with the emails field collapsed:

  ![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/c075271f-7457-449e-bd0e-2ddd4e5d4114)

**Comment by RealRaven2000** [comment]
Here is a test version, can you try it out? It's still a little clunky, when I decrease the top description it seems to increase horizontal width of the dialog, not quite sure how to solve this yet, as these are some idiosyncratic flex properties of the old xul items. I will probably need to rewrite the dialog as HTML5 soon anyway and take full control of all layout rules.

[quickFilters-wx-6.5pre12.zip](https://github.com/RealRaven2000/quickFilters/files/15338003/quickFilters-wx-6.5pre12.zip)

I am calling the system function `window.sizeToContent()` when you collapse / expand one of these sections, they theroretically should include the dialog buttons at the bottom after this.

-----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
Here is another iteration. I heard from a Thunderbird employee today that indeed the legacy dialog is broken so I as a next step will have to convert to an ordinary window and implement the dialog buttons (on the bottom) myself as part of the page; this should also fix flow problems like this. 

Also according to Mozilla the function window.sizeToContent() will be deprecated in future versions so we need to make sure the content is fully responsive and adapts to the window size. This means I will probably make the dialog buttons static and pin them to the bottom, and add vertical scroll bars to the window content if vertical space runs out.

[quickFilters-wx-6.5pre15.zip](https://github.com/RealRaven2000/quickFilters/files/15341102/quickFilters-wx-6.5pre15.zip)

I decided to not use the XUL `<description`> tag and used an ordinary `<p>` for the filter description instead:

![image](https://github.com/RealRaven2000/quickFilters/assets/6314674/a4bf145a-2447-4c68-ace2-41f626fff127)

----

To try the version above download zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by RealRaven2000** [comment]
implemented in v6.5.1 - published 16/07/2024
