### ISSUE TITLE
Filter Log not Running

### ISSUE THREAD

**Issue by KingLek** [RealRaven2000/quickFilters#248]
When i click filter log i get a window that states to use the checkbox  to use the filter log - but it is checked.
I have unchecked and re-checked - nothing
Filters seem to be running fine.
Thunderbird 115.12.2 64 bit
message filters version 6.5.1

**Comment by RealRaven2000** [comment]
that's a built in Thunderbird feature (I didn't add it) - so the best place to report this bug is here:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Thunderbird
