### ISSUE TITLE
"Next Steps" does not over-ride "Settings/Actions."

### ISSUE THREAD

**Issue by StuporDaveOsborne** [RealRaven2000/quickFilters#26]
I mostly use my filters for tagging thousands of emails. Regarding the _Settings -Actions_ for automatically "open editor " and "display filters list." These items appear in "settings" and similarly in "next steps" during filter creation. I have tested these in both directions, enabled or not in "settings." Either way, the _"next steps"_ during filter creation will not over-ride the settings.
   I don't know your intended behavior so I am posting this here.

**Comment by RealRaven2000** [comment]
the way it should work: these checkboxes are (should be) connected to the global setting so once you check  /uncheck them they should remember this as default behavior. Do I understand you correctly that they 
- work during one assistant run
- do not remember when you uncheck?

**Comment by StuporDaveOsborne** [comment]
The check boxes do not seem to relate to the global settings at all.
    I did further testing. I found the config settings and observed that 1: the default for both "editor" and "list""afterCreate" is enabled. However during creation the default "next steps" boxes are unchecked even though the global is enabled. Checking them makes no difference as the steps are already enabled, however UNchecking them also does nothing, the global settings do not change. I have tried this through restarts as well.
   I have tested the checkboxes against globals both on & off, even through restarts. They don't over-ride the globals. Let me know if  you need anything else.

**Comment by RealRaven2000** [comment]
> The check boxes do not seem to relate to the global settings at all.
> I did further testing. I found the config settings and observed that 1: the default for both "editor" and "list""afterCreate" is enabled. However during creation the default "next steps" boxes are unchecked even though the global is enabled. Checking them makes no difference as the steps are already enabled, however UNchecking them also does nothing, the global settings do not change. I have tried this through restarts as well.
> I have tested the checkboxes against globals both on & off, even through restarts. They don't over-ride the globals. Let me know if you need anything else.

So what you're saying is - the checkboxes don't have any effect whatsoever? They are not stored globally, and they do not skip any screens if you uncheck?

**Comment by StuporDaveOsborne** [comment]
That is correct. I did two tests, starting from a restart  with "enabled" and checked, I unchecked during creation and still had both popups. Then I did another restart and created another filter (this time the checkboxes were already unchecked from the last filter) and still had both popups. The global settings were still set to true, no change.

**Comment by RealRaven2000** [comment]
> That is correct. I did two tests, starting from a restart with "enabled" and checked, I unchecked during creation and still had both popups. Then I did another restart and created another filter (this time the checkboxes were already unchecked from the last filter) and still had both popups. The global config settings were still set to true, no change.

That's actually good news - sounds like the preferences aren't properly "wired up" with the configuration database - it shouldn't be too hard to reproduce / fix for the next beta!

**Comment by RealRaven2000** [comment]
Can you test this new beta version below:

https://github.com/RealRaven2000/quickFilters/releases/tag/5.0pre67

It should now show the settings correctly and save them after setting and not ignore them anymore..

**Comment by StuporDaveOsborne** [comment]
Settings are working correctly now.

**Comment by RealRaven2000** [comment]
> Settings are working correctly now.

Good stuff. I am going to close the issue once we go live.  John Bieling cam up with the initial pattern (a hack overwriting preference id with the name) and it works quite seamlessly giving back the automatic dialog to settings binding that we have grown so used to over the last decade.

**Comment by RealRaven2000** [comment]
Fixed in release 5.0
