### ISSUE TITLE
Filter creation (merging) window not sized constrained when many test items.

### ISSUE THREAD

**Issue by StuporDaveOsborne** [RealRaven2000/quickFilters#27]
If a filter is merged to an existing filter with multiple "from" addresses (enough to exceed the size of the monitor screen) using the 'Assistant," when the "edit filter" screen pops up it will not be size constrained to the monitor, requiring multiple grabs of the window edge and resizes.
 TB 78.4 x32bit, QF 5.0 pre 63, Win 7x64

**Comment by RealRaven2000** [comment]
I am trying to add comments with my default browser (Waterfox) but github is really totally acting the b!tch. So I believe this may be a regression specific to the Thunderbird 78 - so it deserves a mention here:

issue #14 

Please make sure the issue can be reproduced with the current beta:
https://github.com/RealRaven2000/quickFilters/releases/tag/5.0pre63

**Comment by RealRaven2000** [comment]
Fixed in release 5.0
