### ISSUE TITLE
Saved attachments of a specific rss feed are saved as empty files (0kB)

### ISSUE THREAD

**Issue by kleajmp** [RealRaven2000/quickFilters#28]
I have set a message filter where Thunderbird automatically saves all attachments **of a specific RSS feed** to a selected file folder.
The attachments are saved as files in the correct file folder.
Now the problem is that all these saved attachments are **empty [0kB]**

![2020-10-25_155727](https://user-images.githubusercontent.com/12158499/97110780-71edf080-16db-11eb-9de2-31ace860d2cb.jpg)
![2020-10-25_155732](https://user-images.githubusercontent.com/12158499/97110783-72868700-16db-11eb-887c-210ab97567d7.jpg)
![2020-10-25_160305](https://user-images.githubusercontent.com/12158499/97110826-96e26380-16db-11eb-8f32-eb2e261e2103.jpg)

**Comment by RealRaven2000** [comment]
I think there are some long standing issues with attachments in Tb68 - you are on Thunderbird 68, right? We are currently converting all my paid Add-ons to 78 and Filtaquilla will then be next; that will be a good occasion to see whether Thunderbird has changed the very volatile attachment code and (hopefully) fix this.

**Comment by RealRaven2000** [comment]
Added the "FiltaQuilla" label.

Please subscribe to https://github.com/RealRaven2000/FiltaQuilla/issues/64 for news on FiltaQuilla conversion to Thunderbird 78 (First steps first).

**Comment by RealRaven2000** [comment]
Let's take this to the [FiltaQuilla issue list](https://github.com/RealRaven2000/FiltaQuilla/issues). There are a ton of attachment related issues there so it might already be there...
