### ISSUE TITLE
Auto-conversion to .eml

### ISSUE THREAD

**Issue by ArtZL** [RealRaven2000/quickFilters#287]
I want all emails received by Thunderbird to be automatically converted to .eml files (or .txt) on my PC.
I'm guessing that FiltaQuilla has that capability, but I need guidance.  

Here's what's happening... When an online sale of my product is made, I receive an email with the details of the sale.  I have a program than runs every 15 minutes looking for .eml files, and my program then performs further processing of the sale.

If FiltaQuilla could also trigger my program, that would be bonus for me.

     Thank you for any help that is offered.
          Art Lieberman

**Comment by RealRaven2000** [comment]
moved to FIltaQuilla, see: https://github.com/RealRaven2000/FiltaQuilla/issues/320
