### ISSUE TITLE
Infinite loop of filtering

### ISSUE THREAD

**Issue by ThiloteE** [RealRaven2000/quickFilters#31]
Dear honorable RealRaven2000,

Specs: Windows 10 x64, Thunderbird 68, latest official version of quickFilters.

I have not tested if this bug persists without using the quickfilters addon.

**Description:**
When having many filters that filter for subject / content, setting them to run automatically interfers with other filters. Apparently there seems to be something wrong with the order of how filters are applied as they seem to try to run at the same time.

I am not sure if it has something to do with the #30 second level filter problem, as i created some filters within my yahoo account to get rid of that problem, but now that yahoo closes access to its mail-groups, i have to migrate to some other e-mail service and i would prefer to use Thunderbird and quickfilters to deal with this problem instead of having to create filters at every single mail account i am registered at.

**Detailed Description of example:**
Step 1) Receive e-mail X into Inbox (Imap-Account, Yahoo.com)
Step 2) Filter 1 and Filter 2 are set to move X from inbox into different folders. Both their requirements for moving are fulfilled. Filter 2 is supposed to run AFTER filter 1, hence if the e-mail has left the inbox, Filter 2 is supposed to stop filtering as there is no e-mail to filter.
Step 3) E-mail is moved to folder 1 AND to folder 2.
Step 4) If i remember correctly for some reason copies of the moved (copied?) e-mails show up in the inbox (?!), then the e-mails get moved to folder 1 and 2 --> more copies --> more moving --> infinite loop
Step 5) I have to close thunderbird because it never stops. It also does not stop when i click on stop filters in the filter menu.

I am afraid to activate all my filters because i am afraid of step 5 xD
Also, shouldn't the problem become worse if i set the filters to "copy" instead of "move" the e-mail? I don't remember if i have tried that one.

**Desired Outcome:** One filter should start working AFTER another filter is done filtering and there should be no loop creating more e-mail. There should be a stop button to stop all automatic filters at the same time, not just stopping manual filtering. There could be an option in the filter creating menu to start running the filter only if filter(s) xyz have run (and finished).

**Cause?** Order of filters not working? E-mail copy and/or move function malfunctioning?

Greetings,

Thilo

**Comment by RealRaven2000** [comment]
one first thing you might try to remedy the second filtering process is to add the action "stop filter execution"

![image](https://user-images.githubusercontent.com/6314674/97776023-11d4cf80-1b5d-11eb-84a2-1a7892fbba8d.png)

this prevent any following filters running on the mail. If you are on Imap, moving emails can take time, so I can imagine that some filter rules may be applied when triggered going further down the list.

**Comment by ThiloteE** [comment]
i will have to experiment with that. I think i tried it once like 3 years back or so. Would it not stop the next filter in the hirarchy completely? Like all the following filters will never run? So This stop filter execution would only make sense with the last filter in the list, right?

Maybe? I don't know. I only see that at the bottom of thunderbird there is some kind of white/greenish loading screen which shows the moving process. From there i deduct that some filters already start even though prior filters are still in progress because the loading screen alternates between different folders (moving e-mails 30/700 to folder xyz) and e-mails are being moved at the same time. It doesn't finish moving one folder first, then the next folder (i have one filter per folder).

**Comment by ThiloteE** [comment]
BUT, i have to admit, i haven't tried this for months now, i will experiment starting from December/January with this when i migrate to a different mailing list.

**Comment by ThiloteE** [comment]
Meanwhile, i found somebody with issues that look similar, except that they included a stop filter order. The bouncing between folders resembles my case, but as you mentioned of course it could have different causes for example the time difference in handling e-mail on imap.

Bug 537501 on Bugzilla
https://bugzilla.mozilla.org/show_bug.cgi?id=537501

![grafik](https://user-images.githubusercontent.com/73715071/98388658-54ae1000-2053-11eb-973b-5ebd62ddad7d.png)

**Comment by ThiloteE** [comment]
I will post this bug in bugzilla. Case closed over here, just please don't close the issue immediatelly, give me a week in case i need to copy parts of the conversation. Thanks in advance. I was able to reproduce the bug manually.

Good news for you: It is not caused by Quickfilters or any other addon! :-)
