### ISSUE TITLE
mouse does not work on folder selection

### ISSUE THREAD

**Issue by ilippert** [RealRaven2000/quickFilters#36]
I am creating a new filter. I want to select which target folder to move the message to. I cannot select folders by mouse, but only by keyboard.

I use this addon on Linux Fedora 33, Wayland.

**Comment by RealRaven2000** [comment]
> I am creating a new filter. I want to select which target folder to move the message to. I cannot select folders by mouse, but only by keyboard.
> 
> I use this addon on Linux Fedora 33, Wayland.

Any keyboard-only method for moving mails should suffice, once the assistant is activated. However, you still have to activate the filter assistant, which you can do via _Tools_ / _Start Filter assistant_ (bottom of tools menu)
![image](https://user-images.githubusercontent.com/6314674/99657253-d5a6d780-2a55-11eb-9296-c3bfd6c2481e.png)
The quickest way is to use `Alt+T`, followed by `Cursor UP` (which will move to the bottom of the menu)

Implementing a keyboard shortcut for the assistant might be a good idea too?

The assistant will then supervise any manual mail movements and fill the folder selector for you automatically when generating the new filter. If your mail is already in the target folder, you can use the context menu (via the [`MENU`] key on your keyboard) on a mail and select _quickFilters: Create Filter from Message_
![image](https://user-images.githubusercontent.com/6314674/99657651-5e257800-2a56-11eb-998f-42a770522870.png)


For moving mails with keyboard only, you can use other add-ons such as quickMove or my own QuickFolders with the quickMove function (only the licensed version gives you a configurable shortcut, which is SHIFT+M by default) - with which you can enter folder name or parent/folder (even with partial matches). It also has additional folder navigation buttons in the main Toolbar and navigation toolbar, for instance "skip unread folder" (`Shift+S`) shortcuts for the first 9 Tabs (`ALT+1` .. `ALT+9`) and `ALT+cursor keys` for navigating sibling folders. You can also use the built-in context menu (again invoke via the [`MENU`] key on your keyboard) and the "**M**ove-to" command for keyboard only.

Once the assistant is active it should catch the mail movement and auto-fill the folder selector which is one of the main points of quickFilters.

**Comment by RealRaven2000** [comment]
> I am creating a new filter. I want to select which target folder to move the message to. I cannot select folders by mouse, but only by keyboard.
> 
looks like I answered the wrong way around. Which window are we talking about, Filter Editor? You say you can't click here?
![image](https://user-images.githubusercontent.com/6314674/99658782-dc364e80-2a57-11eb-961c-c92db5e85309.png)

**Comment by ilippert** [comment]
> looks like I answered the wrong way around. Which window are we talking about, Filter Editor? You say you can't click here?

Yes, indeed. It is precisely this Editor in which I select the Folder, shown in your image (thanks for uploading and clarifying!)

**Comment by RealRaven2000** [comment]
> > looks like I answered the wrong way around. Which window are we talking about, Filter Editor? You say you can't click here?
> 
> Yes, indeed. It is precisely this Editor in which I select the Folder, shown in your image (thanks for uploading and clarifying!)

Ok, this window is a little temperamental regarding the flexible boxes indeed, usually resizing the window reveals the dropdown chevron:
![image](https://user-images.githubusercontent.com/6314674/99660270-0983fc00-2a5a-11eb-9435-423da87b49a6.png)
can you see that on your screen?

**Comment by ilippert** [comment]
Yes, I do see the dropdown chevron that you marked (thanks). Then the list of folders appears (ok). But I cannot select anything with the mouse.

**Comment by RealRaven2000** [comment]
> Yes, I do see the dropdown chevron that you marked (thanks). Then the list of folders appears (ok). But I cannot select anything with the mouse.

ok, if you hover do any of the popup menus automatically expand after a short while? (you do not need to click)
![image](https://user-images.githubusercontent.com/6314674/99665609-c75eb880-2a61-11eb-900d-835507ed55a1.png)

once you click on a folder, can you check whether you see any errors in Error Console? Which exact version of Thunderbird are you running.

**Comment by ilippert** [comment]
78.4.0 (64-bit)
Whilst your "Real Raven" gets highlighted, nothing gets highlighted in my case. No popup menus appear. nothing happens upon hovering.
I checked error console. Nothing changes.

**Comment by RealRaven2000** [comment]
> 78.4.0 (64-bit)
> Whilst your "Real Raven" gets highlighted, nothing gets highlighted in my case. No popup menus appear. nothing happens upon hovering.
> I checked error console. Nothing changes.

Well that sounds like a regression in Thunderbird 78 specific to Linux. definitely file a bug!

**Comment by ilippert** [comment]
ok, thanks. I reported it downstream to the linux distribution.

**Comment by RealRaven2000** [comment]
I will mark this one as closed for now (I don't think I can fix it from my side), feel free to reopen or add comments when you know more!

**Comment by ilippert** [comment]
thanks. I reported it here
https://bugzilla.redhat.com/show_bug.cgi?id=1899644
