### ISSUE TITLE
purchase a quickFilters Pro license is difficult to find

### ISSUE THREAD

**Issue by Bennytl** [RealRaven2000/quickFilters#37]
Would rather have made this a pm, but couldn't find any contact info / e-mail. 
I have to hold my thunderbird at 68 until filtaquilla is ready for 78+. Thought i would buy a pro licence and that started a pretty long hunt for pricing on your site. First i went to https://quickfilters.quickfolders.org/donate.html and couldn't get the purple "get quickfilters pro for 2011" to open a link (doh isn't a link ). I read rest of page and there is donate only info. Then looked for a button on the premium features page, and found nothing. after a pretty long search i found the link in a black text on the premium features page. 
Have looked for it before and given up (ending not donating).

And using filtaquilla not quickfilter, your preferred support of buying a year subscription for quickfilter, seems silly i thought it maybe was a lifetime thing, so I will donate paypall instead. (hate subscription for software)

All the "purchase a quickFilters Pro license." i have clicked ends on the donate page without any "purchase a quickFilters Pro license" links.

Just thought to mention, so you can get donations and get filtaquilla done faster :o)

**Comment by RealRaven2000** [comment]
> Would rather have made this a pm, but couldn't find any contact info / e-mail.
> I have to hold my thunderbird at 68 until filtaquilla is ready for 78+. 

Here is a preview version.
https://github.com/RealRaven2000/FiltaQuilla/releases/tag/3.0pre40

Conversion was gruelling, many days of banging my head against the wall. And we're not even a full blown "mail extension" based on APIs yet, that conversion will happen next year. We might well not be allowed many of the features with APIs only, so I need to do a lot of begging and arguing. (For instance they may simply say no to any of the JavaScript stuff)

> Thought i would buy a pro licence and that started a pretty long hunt for pricing on your site. First i went to https://quickfilters.quickfolders.org/donate.html and couldn't get the purple "get quickfilters pro for 2011" to open a link (doh isn't a link ). I read rest of page and there is donate only info. Then looked for a button on the premium features page, and found nothing. after a pretty long search i found the link in a black text on the premium features page.
> Have looked for it before and given up (ending not donating).
> 
> And using filtaquilla not quickfilter, your preferred support of buying a year subscription for quickfilter, seems silly i thought it maybe was a lifetime thing, so I will donate paypall instead. (hate subscription for software)

Yeah I don't like subscriptions either. But there is one difference: If I write software (an executable) for an operating systme (like Windows) it will work for 10-20 years and it won't break every few months. We have not such security running on the behemoth that is Thunderbird (which is based on Firefox / Mozilla code base and then some) they constantly change stuff and we need to rewrite our Add-ons./ This years they pulled the plug on legacy Add-ons so we got in as "mail extensions with experimental APIs" which is sort of a back door. I spent 3,500 bucks on external developers to get to the current place. 

These experiments will eventually be phased out - which means more rewriting. I am happy to sell permanent license when Thunderbird guarantees that they have APIs that give access to ALL the functionality necessary and the APIs won't change. At the earliest end of 2022 but it might well go on for a few years. 

> All the "purchase a quickFilters Pro license." i have clicked ends on the donate page without any "purchase a quickFilters Pro license" links.

If you wanted a license for quickFilters you can just do that on the "pro" tab:
![image](https://user-images.githubusercontent.com/6314674/100474665-19928000-30d9-11eb-9be6-3113df90a899.png)
there are also sometimes direct links for special offers on the version page, e.g.:
https://quickfilters.quickfolders.org/version.html#4.4.1

> Just thought to mention, so you can get donations and get filtaquilla done faster :o)
yes I have the donation option on the quickFilters page and did some fund raising for it that way. I really spent about 60 hours converting it so far, not bad for a "free as in beer" software. See the conversion thread with all the latest news, here:

https://github.com/RealRaven2000/FiltaQuilla/issues/64

just leave a comment or +1 there and you will be notified on news. All latest tryout versions are here:
https://github.com/RealRaven2000/FiltaQuilla/releases

**Comment by RealRaven2000** [comment]
FiltaQuilla now supports direct donations on the webpage, here:

https://quickfilters.quickfolders.org/filtaquilla.html#donate

I also updated the text and added a link to the web shop just in case
