### ISSUE TITLE
automatically print attachments | Anhänge automatisch ausdrucken wäre sehr hilfreich

### ISSUE THREAD

**Issue by githubphantomas** [RealRaven2000/quickFilters#40]
Hej RealRaven2000,
I recently read a notice, that you are about to continue this project. I feature that I was really looking for is to print automatically e-mails and their attachment(s). As far as I know there is still no add-on for Thunderbird, only paid add-ons for outlook or stand-alone-software. So this might be a new filter-feature the world is looking for.

Hallo RealRaven2000,
ich las kürzlich, dass du dich dem Projekt annimmst, QuickFilters weiterzuentwickeln. Ein Feature, nach dem ich schon lange suche ist ein Add-On, um Anhänge von E-Mails automatisch zu drucken. Soweit ich weiß gibt es dafür aktuell kein Add-On für Thunderbird (nur für ältere Vorversionen finden sich Beiträge dazu im Internet, die z. B. FiltaQuilla mit einem anderen Add-On kombinieren). Für Outlook gibt recht teure Add-Ons oder auch eigenständige Software zu Preisen, die sich eine Schule nicht leisten kann und viele Unternehmen sicherlich auch nicht. Ich selbst bin Lehrer und auf der Suche nach einem Add-On, so dass Vertretungsmaterial (hauptsächlich PDFs) unkompliziert in die Schule geschickt werden kann. Vielleicht ist das ja eine sinnvolle Erweiterung für das Projekt QuickFilters; ich denke, dass viele andere ebenfalls nach einer solchen Lösung suchen. Eine Pro-Version würde ich dann auch kaufen ;) 
Vielen Dank und viele Grüße aus Brakel in NRW
githubphantomas

**Comment by RealRaven2000** [comment]
Der korrekte github für neue Filter Aktionen ist definitiv FiltaQuilla (welches ich auch soweit möglich pflege):

https://github.com/RealRaven2000/FiltaQuilla/issues
quickFilters ist mehr für Management und troubleshooting zuständig.

**Comment by githubphantomas** [comment]
OK, and as I realize now, there is already a similar post: 
OK, und wie ich gerade sehe, gibt es da schon einen ähnlichen Post:

https://github.com/RealRaven2000/FiltaQuilla/issues/38

Thanks for your quick response!
Danke für deine schnelle Antwort!

**Comment by RealRaven2000** [comment]
Thanks - feel free to expand RealRaven2000/FiltaQuilla#38 and I will close this one here!
