### ISSUE TITLE
What "filter assistant"?

### ISSUE THREAD

**Issue by MarjaE2** [RealRaven2000/quickFilters#43]
I can't find a full manual, just the short explanation here:

https://addons.thunderbird.net/en-US/thunderbird/addon/quickfilters/

"Activate the filter assistant. ..."

What "filter assistant"? There's a "Quick Filter" icon in the toolbar, but it just shows or hides the "Unread," "Starred," etc. options.

**Comment by MarjaE2** [comment]
P.S. Thunderbird had not tecognized the filter. Solved that.

**Comment by RealRaven2000** [comment]
> I can't find a full manual, just the short explanation here:
> 

The support site is here:
https://quickfilters.quickfolders.org/
A bunch of videos that explain how to use quickFilters is here:
https://www.youtube.com/playlist?list=PLApv7QYQO9nSUTaBbX8ZTz2XcIt61l73V

> https://addons.thunderbird.net/en-US/thunderbird/addon/quickfilters/
> 
> "Activate the filter assistant. ..."
> 
> What "filter assistant"? There's a "Quick Filter" icon in the toolbar, but it just shows or hides the "Unread," "Starred," etc. options.

It is activated when you click the button that is automatically added to your toolbar:
![image](https://user-images.githubusercontent.com/6314674/105338623-ae929080-5bd3-11eb-9ca0-52aa6003806e.png)

Once clicked, it turns red:
![image](https://user-images.githubusercontent.com/6314674/105338670-bb16e900-5bd3-11eb-9441-c9c41a559549.png)
...and shows this message at the bottom:
![image](https://user-images.githubusercontent.com/6314674/105338706-c538e780-5bd3-11eb-9b4b-d03b9e475158.png)

then you start moving mails to "teach" quickFilters what to do. It can create filters accordingly using the filter assistant:

![image](https://user-images.githubusercontent.com/6314674/105338849-e994c400-5bd3-11eb-8079-848a4ab8bcc3.png)

If you have already moved the mail earlier you can also generate a filter from it, via right-clicking the message and selecting "quickFilters: create filter from message"
![image](https://user-images.githubusercontent.com/6314674/105338906-fd402a80-5bd3-11eb-8391-ddb006251443.png)
