### ISSUE TITLE
Variables @SUBJECT@ and others

### ISSUE THREAD

**Issue by kodorevi8ulis** [RealRaven2000/quickFilters#54]
Is there any way to use regexp for variables like @subject@ ?

for example , i want to run a program with parameter a part of @subject@

**Comment by RealRaven2000** [comment]
I think you need to ask the question over at [filtaquilla](https://github.com/RealRaven2000/FiltaQuilla/issues)! That has an action for executing programs, see:

https://quickfilters.quickfolders.org/filtaquilla.html#run_file

**Comment by RealRaven2000** [comment]
> I think you need to ask the question over at [filtaquilla](https://github.com/RealRaven2000/FiltaQuilla/issues)! That has an action for executing programs, see:
> 
> https://quickfilters.quickfolders.org/filtaquilla.html#run_file

PS: if you need quickFilters to help generate filters automatically that carry out the actions provided by filtaQuilla, you can make some custom templates.

**Comment by kodorevi8ulis** [comment]
sorry for the wrong section :)
