### ISSUE TITLE
Fixed translation

### ISSUE THREAD

**Issue by ashed** [RealRaven2000/quickFilters#55]
I fixed translation in these resources:
quickFilters@axelg.com/chrome/locale/ru/register.dtd
quickFilters@axelg.com/chrome/locale/ru/overlay.properties
quickFilters@axelg.com/chrome/locale/ru/filterList.dtd
quickFilters@axelg.com/chrome/locale/ru/options.dtd
quickFilters@axelg.com/chrome/locale/ru/filters.properties

Add it to upstream please.

[ru.zip](https://github.com/RealRaven2000/quickFilters/files/6272898/ru.zip)

**Comment by RealRaven2000** [comment]
Excellent, thank you ! Just merged. If you like a free quickFilters Pro license, please get in touch via the support tab!

**Comment by ashed** [comment]
"What shall I write for translation credentials in the credits?"
Igor Zhigunov aka ashed

**Comment by RealRaven2000** [comment]
implemented in 5.2.1 published today. if you like you can also have a look at the file `messages.json` here
https://github.com/RealRaven2000/quickFilters/tree/ESR78/_locales/ru

these messages are shown whenever quickFilters is installed for the ifrst time or updated (the exact set of which messages are shown depends on whether the user has a license and whether it is current, expired or will soon expire - so it's kind of modular)
