### ISSUE TITLE
No Can See

### ISSUE THREAD

**Issue by baqwas** [RealRaven2000/quickFilters#59]
Hello!

With trepidation, I'm logging an issue since I'm a total newbie. Apologies for any misunderstanding on my part.

Downloaded **FiltaQuilla** (per TB 78.9.1 Ubuntu 20.10 Add-ons Manager). I am unable to see any menu item (or toolbar) to invoke the extension. I installed Quicktext earlier and can see it listed under the Tools drop-down menu.

I've exited my TB session and restarted it. In TB _Under Manage Your Extensions_, **FiltaQuilla** is clearly enabled but I still do not know where/how to launch/invoke it.

What is **my** mistake, please? Thanks.

Kind regards.

**Comment by RealRaven2000** [comment]
that's a FiltaQuilla question - wouldn't that be better on the [FiltaQuilla issue tracker](https://github.com/RealRaven2000/FiltaQuilla/issues)?

If you click on Add-ons you can access FiltaQuilla settings via the "..." menu and selecting Options:

![image](https://user-images.githubusercontent.com/6314674/115107181-2ec15b80-9f61-11eb-9553-d7307f37ff7e.png)

Select what additional search terms / actions you need there. Don't select them all. When you add stuff multiple times you may see duplications in the drop down filter editor, which will be resolved by restarting Thunderbird.

![image](https://user-images.githubusercontent.com/6314674/115107228-7c3dc880-9f61-11eb-89e6-829f9653a87e.png)

by the way, you can see this documented and the latest modifications on the change log which opens automatically when you update FiltaQuilla:
https://quickfilters.quickfolders.org/fq-versions.html#3.1

In all of my Add-ons, you can access the change log any time by clicking on the version number in settings:
![image](https://user-images.githubusercontent.com/6314674/115107311-f5d5b680-9f61-11eb-8f33-db877087bf4b.png)

**Comment by baqwas** [comment]
Hello @RealRaven2000,
Thank you very much for your professional response! It is really a pleasure to receive such a response even when I've submitted the "_inquiry_" into the wrong site.

The only difference between your screen shot and my mine is that you have _Options_ and I have _Preferences_ in the drop-down for FiltaQuilla under Add-ons Manager. version. Not an issue anymore now that I understand what I have to do. Beyond that I agree and understand that I have to use it for my intended application of the add-on. Thanks again.

Kind regards.
