### ISSUE TITLE
Make quickFilters compatible with Thunderbird 91

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#70]
bugtracker for all regressions related to the upcoming Thunderbird ESR version 91.0

You can already test quickFilters with 91.0b2. Latest test version:

[quickFilters-wx-5.3pre131.zip](https://github.com/RealRaven2000/quickFilters/files/6864287/quickFilters-wx-5.3pre131.zip)

**Comment by RealRaven2000** [comment]
Released [5.3.1](https://addons.thunderbird.net/thunderbird/addon/quickfilters/versions/5.3.1) on 05th of August 2021. Going to keep this issue open for a month to catch any incompatibilities. If you suspect regressions are caused by Thunderbird 91 please add in a comment below, or raise a new issue!

**Comment by toanlc0912** [comment]
Not sure if anyone came across it yet but recently after upgrading to Thunderbird 91, I have problem with merging filter function.
The merging window pops up with 2 boxes ticked as image.
Both "merging filters" and "create new filter" are ticked, which results in creating new filter if we continue.
![2021-08-14 19_22_02-Inbox - Mozilla Thunderbird](https://user-images.githubusercontent.com/7235986/129446206-09c31644-d957-4bb4-a120-a905ea443893.png)

**Comment by toanlc0912** [comment]
> 
> 
> Not sure if anyone came across it yet but recently after upgrading to Thunderbird 91, I have problem with merging filter function.
> The merging window pops up with 2 boxes ticked as image.
> Both "merging filters" and "create new filter" are ticked, which results in creating new filter if we continue.
> ![2021-08-14 19_22_02-Inbox - Mozilla Thunderbird](https://user-images.githubusercontent.com/7235986/129446206-09c31644-d957-4bb4-a120-a905ea443893.png)

Just some more information on this one.
- Fresh created filter will be working just fine when merging. ("Create a New Filter" won't be ticked)
- I tried to delete all filters and import again but that doesn't work.

**Comment by toanlc0912** [comment]
**Sorry to bother again. After recent update (I had quickFilter updated yesterday), this issue no longer happens.**

**Comment by RealRaven2000** [comment]
> **Sorry to bother again. After recent update (I had quickFilter updated yesterday), this issue no longer happens.**
> I'm not sure if the update fixed it or ticking the option "Automatically select Merge"

are you running 5.3.1? Or an updated version of Thunderbird?

**Comment by toanlc0912** [comment]
I'm using 5.3.1 on TB 91.
