### ISSUE TITLE
Example subject manipulation filter not working

### ISSUE THREAD

**Issue by sandybrownlee** [RealRaven2000/quickFilters#73]
This is on Thunderbird 78.13.0 64 bit (Linux Mint) - FiltaQuilla 3.2

I use a variation of the example javascript action filter to amend the subject on some emails (my mailserver adds the prefix {SPAM?} quite often: rarely is this correct, but it has the ironic effect that when I reply to such emails, the replies end up in junk folders). The filter simply replaced the SPAM tag with a couple of underscores so I could see where it happened:

```
for (let index = 0; index < msgHdrs.length; index++)
{
  let hdr = msgHdrs.queryElementAt(index, Ci.nsIMsgDBHdr);
  hdr.subject = hdr.subject.replace("{SPAM?}", "__");
}
```

This has recently started failing with this error in Thunderbird's console:

`msgHdrs queryElementAt is not a function`

I don't know the cause as I'm not all that familiar with Thunderbird's update cyctem. Maybe it's an API change somewhere. Anyway, I fixed it by doing this:

```
for (let index = 0; index < msgHdrs.length; index++)
{
    msgHdrs[index].subject = msgHdrs[index].subject.replace("{SPAM?}", "__");
}
```

This now works fine. Assuming there is nothing else wrong with the above, it might be worth updating the example in the documentation for javascript actions to reflect that. (I was also not clear on what nsIMsgDBHdr objects - the type of the msgHdrs array - actually contain - is it possible to have a link to docs on that somewhere?)

Thanks!

**Comment by RealRaven2000** [comment]
Please, if you still have this issue - add it to the [FiltaQuilla github.](https://github.com/RealRaven2000/FiltaQuilla/issues/130) THis one is for quickFilters.

**Comment by sandybrownlee** [comment]
I do apologise, I'm not sure how I managed to stumble into the wrong project repo.

**Comment by AlexFinch** [comment]
Thanks for this example. Saved me a lot of time. Could this example be put in the documentation for filtaquila as it  works.
