### ISSUE TITLE
Question/Feature Request: Filter by Relative Dates

### ISSUE THREAD

**Issue by infinitelyintrigued** [RealRaven2000/quickFilters#75]
Hi, is there a way to filter by relative dates (today, yesterday, 3 weeks ago, etc.)? For example, I want to see messages that I received today. I created and use a search folder using the Outlook desktop app, but have not found a way to do this using Thunderbird/quickFilters. Thank you.

**Comment by RealRaven2000** [comment]
> Hi, is there a way to filter by relative dates (today, yesterday, 3 weeks ago, etc.)? For example, I want to see messages that I received today. I created and use a search folder using the Outlook desktop app, but have not found a way to do this using Thunderbird/quickFilters. Thank you.

Sure - when setting up a filter, you can add the standard search method "Age in days" :

![image](https://user-images.githubusercontent.com/6314674/135725124-79afbb17-6cd8-4e58-8a12-ed2f6ef88ca5.png)

If you want to generate many new filters with a certain age pre-populated you can create a filter template using advanced settings / custom templates:

![image](https://user-images.githubusercontent.com/6314674/135725142-c8ed4af6-ad9d-4316-9dd3-d46a490e4d7e.png)

**Comment by infinitelyintrigued** [comment]
Thank you for these tips!
It appears Thunderbird goes by hours instead of days. Less than 1 day finds messages received within the last 24 hours -- unlike Outlook does. But this will do for now. I really like your quickFilters, by the way!
