### ISSUE TITLE
No changes but save attachment in filters is no more working

### ISSUE THREAD

**Issue by ruttan2** [RealRaven2000/quickFilters#79]
Hi, I have been using the save attachment function inside 2 filters for a few days, it was working perfectly:

- Then without any apparent reason it has stopped
- I have checked that the event fires normally (it also make a sound)
- I have checked that the folder is not corrupted or inaccessible but... nothing
- I use Windows 10 Pro and I have tried to run Thunderbird as an administrator but... nothing

What can I do? Thanks for the help.

**Comment by RealRaven2000** [comment]
if it is an attachment save / detachment function, then this is a FiltaQuilla issue. try to do whatever steps (such as moving the mail or tagging) is done beforehand.

**Comment by RealRaven2000** [comment]
What version of FiltaQuilla are you using?

**Comment by RealRaven2000** [comment]
Please follow up on the FIltaQuilla github:

https://github.com/RealRaven2000/FiltaQuilla/issues?q=is%3Aissue+is%3Aopen++attachment+in%3Atitle

Closing the issue here in quickFilters for now, as quickFilters is not involved during the process of _running_ filters.
