### ISSUE TITLE
Check for duplicate attributes when adding conditions to existing filters

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#8]
The mess I have got myself into before I realized I was duplicating filters:
![image](https://user-images.githubusercontent.com/6314674/78369329-e8e75e80-75bc-11ea-8b3d-5079effdaa46.png)

Quickfilters allow duplicate attributes to be added to existing filters. When using Thunderbird with an IMAP account often filters fail to work.  

This means you can sometimes accidentally add filters again thinking a filter does not already exist.. 

If you add the filter again to an existing filter with quickfilters, quick filters allows you, resulting in duplicate attributes in the existing filter.

Also a nice to have would be a tool to find and remove any duplicate attributes that already exist.

Originally reported on mozdev.org [bug 26737](https://www.mozdev.org/bugs/show_bug.cgi?id=26737) by Rob L. on 2019-12-09

**Comment by tracyphasespace** [comment]
Also Spammers are clever enough to change attributes such as their send email by a small one letter or symbol. A check of domain name could prompt a suggestion that it is spam.

**Comment by RealRaven2000** [comment]
> Also Spammers are clever enough to change attributes such as their send email by a small one letter or symbol. A check of domain name could prompt a suggestion that it is spam.


You can already filter by domain name. What you want is a nbew action "make a suggestion that something is spam"?

I think this would be a good fit for FiltaQuilla, which is in the business of adding new conditions / filter actions. quickFilters cannot do this.

**Comment by RealRaven2000** [comment]
I think this one should be fixed now at last (if it is about duplication of search terms in existing filters when merging)
