### ISSUE TITLE
same message as file

### ISSUE THREAD

**Issue by Blisk** [RealRaven2000/quickFilters#82]
When I use this option I get empty file or file with 0 bytes.

**Comment by RealRaven2000** [comment]
Not sure what you mean -if you save as file then it may be FiltaQuilla issue? Again screenshot or export the filter...

**Comment by Blisk** [comment]
Hi
No I have settings in FiltaQuilla filter "Save message as file"
![slika](https://user-images.githubusercontent.com/2773050/143781733-bfd08eac-87af-4e52-8e51-f00bbf6fda19.png)

**Comment by RealRaven2000** [comment]
I have tested it hrere with FiltaQuilla - but it works for me. Can you check the error log when you run it manually?
Ctrl+Shift+J - any additional messages when you execute the filter. Also, this should be reported no here (quickFIlters) but in the Filtaquilla github:
https://github.com/RealRaven2000/FiltaQuilla/issues
