### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by jirasekuo** [RealRaven2000/quickFilters#83]
Hi. I have a problem with filters - printing emails. please help me.

quickfiters - 3.2, TB - 91.3.2

Filter action "Print" not working, if i try print message from menu, print is working, but if print action called from filter action, print not work....

thanks a lot

**Comment by RealRaven2000** [comment]
This is a FiltaQuilla issue - please see / comment on the github for FiltaQuilla here:

https://github.com/RealRaven2000/FiltaQuilla/issues/130
