### ISSUE TITLE
IDEA  | Copy/Paste virtual folder

### ISSUE THREAD

**Issue by youpi2000** [RealRaven2000/quickFilters#84]
Thunderbird doesn't offer to copy/paste a virtual folder

But, sometimes, the same Virtual folder is required in severals differrents CATEGORY\Tab

I suggest your development of a functionality to copy/paste a virtual folder

**Comment by RealRaven2000** [comment]
> Thunderbird doesn't offer to copy/paste a virtual folder
> 
> But, sometimes, the same Virtual folder is required in severals differrents CATEGORY\Tab

not sure what you mean with Category (unless you mean the QuickFolders Add-on). Copy / paste: what exactly do you mean, assigning different categories to a QF Tab without using the context menu (QF Commands / set category)?
