### ISSUE TITLE
FiltaQuilla - Filter entry field small and won't expand

### ISSUE THREAD

**Issue by johndoe1969** [RealRaven2000/quickFilters#88]
I am running Fedora 35 and Thunderbird 91.4.0.  I just upgraded from Thunderbird 78.

When I open my filters to either edit an existing one or create new one, the "Field" into which you type the filter is very small when selecting Subject Regex Match, Header Regex Match, Body Regex Match, BCC, or Folder Name (only options I choose with FiltaQuilla).

Not the filter name, but where you actually type in what you are filtering for.

If you just select any of the standard options that already come with Thunderbird then the field is normal/large.

![Screenshot1](https://user-images.githubusercontent.com/50086425/149639727-38cee29c-f565-44fe-b450-a6e87c1d40e8.png)
![Screenshot2](https://user-images.githubusercontent.com/50086425/149639728-32ce05c4-1e11-4026-9b52-2e7a0ddbc246.png)

 I have disabled/enabled FiltaQuilla and restarted Thunderbird numerous times.  Any ideas???

**Comment by RealRaven2000** [comment]
tracked and fixed on the filtaquilla github:

https://github.com/RealRaven2000/FiltaQuilla/issues/145
