### ISSUE TITLE
Create filter by subject - option to allow full subject if `[string]` in line

### ISSUE THREAD

**Issue by pfagomez** [RealRaven2000/quickFilters#89]
Background:

all emails I get on an inbox have the tag [something]. Everytime I want to create a quickfilter by subject I have to copy and paste it manually, because the automatic detection only detects the "tag" [something] and deletes everything else. I see how this could be useful, but in my case it makes it absolutely useless.

**Comment by RealRaven2000** [comment]
> Background:
> 
> all emails I get on an inbox have the tag [something]. Everytime I want to create a quickfilter by subject I have to copy and paste it manually, because the automatic detection only detects the "tag" [something] and deletes everything else. I see how this could be useful, but in my case it makes it absolutely useless.

ok, so what you are saying is that you would like to be able to disable this feature - as you would like the complete subject line copied into the search condition?

**Comment by pfagomez** [comment]
yes! 
ideally it creates one condition with the (each) tag and one with the remaining text.
acceptably it creates one condition with the whole subject

**Comment by RealRaven2000** [comment]
Here is a test version. After installation, open the config editor using _Thunderbird Preferences-General - [Config Editor...]_
(The button is at the bottom right). IN the search field enter `subjectDisableKeywordsExtract` . Set this setting to true:

`extensions.quickfilters.subjectDisableKeywordsExtract = true`

![image](https://user-images.githubusercontent.com/6314674/149940493-bd0efbe0-b1c8-41b7-9356-5330a46c70ea.png)

This will activate the alternative behavior. Test version below:

[quickFilters-wx-5.3.3pre13.zip](https://github.com/RealRaven2000/quickFilters/files/7889164/quickFilters-wx-5.3.3pre13.zip)

to install, download the zip file, then drag it into Thunderbird Add-ons manager. on the popup, click the Add button.

**Comment by RealRaven2000** [comment]
Once the testing phase is over and this setting proves to be useful I will add a global option to quickFilters settings / Advanced to toggle the new switch.

**Comment by pfagomez** [comment]
unwanted behaviour is gone! Thank you very much for the update.
However: now it creates one filter for each reply:

[string] original subject

RE: [string] original subject

RE: RE: [string] original subject

RE: RE: RE: [string] original subject

but I guess that is better.

**Comment by RealRaven2000** [comment]
> unwanted behaviour is gone! Thank you very much for the update. However: now it creates one filter for each reply: [string] original subject RE: [string] original subject RE: RE: [string] original subject RE: RE: RE: [string] original subject but I guess that is better.

Ok - so what you are saying is that you create the filter by moving a bunch of messages to a folder (rather than the first one)? I would just move the first message (with assistant active), then create the filter and click "run filters" as the last step to test the condition - this way you avoid duplication of the filter conditions and get a test of your new filter for free!

Since (by default settings) the filter list shows with the new filter highlighted the test step is only a single click.

**Comment by RealRaven2000** [comment]
I added a user interface (option on the Actions tab) for setting / unsetting this new behavior. Latest test version:

[quickFilters-wx-5.4pre24.zip](https://github.com/RealRaven2000/quickFilters/files/7936135/quickFilters-wx-5.4pre24.zip)

to install, download the zip file, then drag it into Thunderbird Add-ons manager. on the popup, click the Add button.
