### ISSUE TITLE
option to move/copy mail not only from Inbox, but from any user defined folder

### ISSUE THREAD

**Issue by sbi6c** [RealRaven2000/quickFilters#95]
**Hello and many thanks for all the good in your work.**

**Could you please add a functionality for each filter defined in quickFilters to have the ability to use not only the "Inbox" as its input folder, but also any other folder selected by the user.** The filter then not only can process (move/copy) the e-mail from the "Inbox" folder to a user defined folder as it is now, but would also have the option for the user to define which folder to move/copy the email from.

**Use case:** Certain free e-mail service servers automatically put e-mails into folders like "Promotions", "Junk", etc., but have no options, e.g. no setup switches, to influence this automatic behavior (or have incorrectly working or not adaptively working Junk filtering = it is not able to "learn" which emails the user actually wants to be perceived as "Junk" and which not, and moves incorrect messages to Junk, yet before the email client processes them). So each time the user wants to check for new e-mails (s)he end up in looking into several folders one-by-one, instead of just looking into the "Inbox". Here the quickFilters with this new functionality would copy (all / certain) e-mails from Promotions, Junk (e.g. when Junk filtering works incorrectly / is not adaptive, then the quickFilters would "deputy" this functionality and do the messages' necessary movements based on user's filter setup).

Many other useful possibilities open then, for example to take only certain messages from Promotions to Inbox, but not all, as the server's Promotions filtering can be partially okay. Etc.....;)

_This could be partially resolved by using of an email client with "Unified Inbox" functionality. This however takes all e-mails from all folders marked to be included in the "Unified inbox", instead of picking and including only certain messages based on user defined criteria, for example in the event of incorrectly working mail server Junk filtering, when some messages in Junk folder should in fact stay in Inbox. With this new-requested functionality the quickFilters would do the necessary movement of such incorrectly Junked messages back to Inbox._

Thanks a lot, stay safe and healthy

**Comment by RealRaven2000** [comment]
See issue #6 and issue #30 - let's discuss there - marking this as duplicate.
