### ISSUE TITLE
Make quickFilters compatible with Thunderbird 102 (ESR 2022/23)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/quickFilters#97]
Like every year, I am planning for quickFilters to be compatible with the next ESR release of Thunderbird (102)

Please add your bug reports below.

I recommend starting with beta 99 for testing, download from here:
https://www.thunderbird.net/en-US/#channel

When adding bugs below please write down the exact version of Thunderbird, expected behavior and observed behavior.

**Comment by RealRaven2000** [comment]
Quick test version from the first branch - this is based on the previous release 5.3.2 (master)

[quickFilters-wx-5.5pre2.zip](https://github.com/RealRaven2000/quickFilters/files/8238272/quickFilters-wx-5.5pre2.zip)

to install, download the zip file above and then drag into Thunderbird Add-ons Manager. New branch on github with source code is here: 
https://github.com/RealRaven2000/quickFilters/tree/ESR102

(I need to upmerge 5.4 from the ESR91 branch to include the latest changes!)

**Comment by RealRaven2000** [comment]
Latest beta - this fixes some issues with the sliding notification panel not displaying from Tb99 onwards. It also brings back the quickFilters icon in these areas, for instance when the assistant message shows:

![image](https://user-images.githubusercontent.com/6314674/162950117-d55688c0-db6f-4fae-8495-3bb3736e86bb.png)

[quickFilters-wx-5.4.1pre9.zip](https://github.com/RealRaven2000/quickFilters/files/8472407/quickFilters-wx-5.4.1pre9.zip)

to install, download the zip file above and then drag into Thunderbird Add-ons Manager.

**Comment by aprojanos71** [comment]
Thx! I installed quickFilters-wx-5.5pre2.zip but where are my filters?

**Comment by RealRaven2000** [comment]
I made another version bump for the current beta (100.0b2)

> Thx! I installed quickFilters-wx-5.5pre2.zip but where are my filters? edit 1: And "undefinedundefined" appears below... edit 2: And I can't close Thunderbird

you should have scrolled down for 5.4.1pre9 (lkast one in the thread) - but that has max version 99.* so I just bumped it up to 102.*. So here is the latest bumped version:

[quickFilters-wx-5.4.1pre19.zip](https://github.com/RealRaven2000/quickFilters/files/8505041/quickFilters-wx-5.4.1pre19.zip)

- the reason for the lower version number (5.4.1 instead of 5.5 - that one was an accident) is that there is no real new stuff apart from the regression fixes for Thunderbird 102 mentioned above.

As always: to install, download the zip file above and then drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
> Thx! I installed quickFilters-wx-5.5pre2.zip but where are my filters?

Filters are actually stored by Thunderbird itself, in files called msgFilterRules.dat - quickFilters is not involved in this operation at all! Check in your profile folder whether you can find any (there should be one per mail account). I highly recommend regularly backing up your Thunderbird profile folder to avoid data loss. Extra especially if you use Thunderbird beta versions!

But you can also backup / restore your folders in a more friendly format using the quickFilters json format from the message filters dialog:
![image](https://user-images.githubusercontent.com/6314674/163799225-af3d5268-d357-4501-9792-911d82231cbb.png)

you can then restore your filter from the _Restore filters_ button beside:

![image](https://user-images.githubusercontent.com/6314674/163799284-0c224fa0-e148-4623-b33a-6592e1cb7eb0.png)

You just have to make sure to select the correct account to load the filters into!

note that filters will only be overwritten if they have exactly the same name - unfortunately Thunderbird does not store any other meta-information (like a unique ID or last edited date) and Add-ons cannot add such information.

**Comment by aprojanos71** [comment]
QuickFilters 5.4.1pre19 works fine on 100.0b2 (64 bit)!
Thanks!

**Comment by RealRaven2000** [comment]
Latest Prerelease tested on Thunderbird 101.b3 is below, max compatibility is 102.0 so it should work with release.

<b>Improvements</b>
<ul>
<li> <a href="https://github.com/RealRaven2000/quickFilters/issues/100">[issue 100]</a> Improve location of toolbar buttons when installing quickFilters

When installing quickFilters for the first time, the new buttons appear to the right of the application menu. A better location would be to the left of the search box, aligned to the last visible button (in this example "Quick Filter")
</li>
<li> Increasing maximum TB version for next ESR - Thunderbird 102.0 is planned to be supported from now on.</li>
<li> Added new domain part extractors for custom templates: Root domain, Subdomain, Domain name extension. These will usually work reliably depending on how exotic your domain extensions are. However it doesn't check against the database of extensions that look like domains, such as "pharma.pro", here the algorithm will falsely assume that the URL "tools.pharma.pro" consists of:

subdomain = tools, root domain = pharma, extension = pro 

  - even though in reality it is:
  
root domain = tools, extension = pharma.pro
  
I am not doing an online sanity check here, so double check when you use these functions to create new filter templates.</li>
<li> 
Added a help panel in custom template editor that explains the placeholder action "set priority to normal". When the assistant creates a new filter it will always add the appropriate action (such as move to current folder or tag with the current tag) based on what the user did. Since the filter editor needs at least one action the custom template editor just uses a "neutral" action (set priority to normal) as a placeholder. This should be left alone - do not try to set a "move to folder action" unless you want to do it and expect this action to be hardcoded in all filters you want to generate with this template.
</li>
<li>
Added more transparency for features that require a Pro license. You can use these features a limited number of times the remaining of which will now be displayed in the license notification at the bottom of the screen. All usage counts will be reset when this new version is installed.
</li>
</ul>

<b>Bugs Fixed</b>

<ul>
<li> Fixed "copy" icon in filter list removed in TB102. </li>
<li> Fixed sliding notification panels for Thunderbird 99 and higher.</li>
<li> Fixed sliding notification icon for Thunderbird 91 </li>
<li> Fixed icon on OS notification (Run filters on folder / selected mails...) </li>
<li> Fixed a problem with alias email addresses in license.</li>
<li> Tested with <a href="https://www.betterbird.eu/">Betterbird</a> so that new can be generated. To do: intelligent merging into subgroups depending on template. E.g.  subject AND (from OR from OR from)</li>   
</ul>

[quickFilters-wx-5.4.1pre62.zip](https://github.com/RealRaven2000/quickFilters/files/8727320/quickFilters-wx-5.4.1pre62.zip)
2

As always: to install, download the zip file above and then drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
My batch file was slightly incorrect in naming the version number wrong, so here is one with a matching version number (5.5pre*** instead 5.4.1pre***)

[quickFilters-wx-5.5pre63.zip](https://github.com/RealRaven2000/quickFilters/files/8727383/quickFilters-wx-5.5pre63.zip)

As always: to install, download the zip file above and then drag into Thunderbird Add-ons Manager.
