### ISSUE TITLE
Thunderbird 100.0b2 (64-bit)

### ISSUE THREAD

**Issue by aprojanos71** [RealRaven2000/quickFilters#99]
![image](https://user-images.githubusercontent.com/6314674/163727793-6d22e35a-5ae2-4b05-a55d-d444d85b14d0.png)

**Comment by aprojanos71** [comment]
Not working.

**Comment by aprojanos71** [comment]
When I start the Quickfilter, a yellow error message pops up below and I can't exit Thunderbird.
And where are my filters?

**Comment by aprojanos71** [comment]
Is the license expired ???

**Comment by RealRaven2000** [comment]
duplicate of issue #97 - please try the versions uploaded there for running Thunderbird betas.
https://github.com/RealRaven2000/quickFilters/issues/97

**Comment by RealRaven2000** [comment]
please don't link to external content (as you did previously) - you can paste images here directly:

> ![image](https://user-images.githubusercontent.com/6314674/163727793-6d22e35a-5ae2-4b05-a55d-d444d85b14d0.png)
